---
title: "salidas_InformeFinal"
output:
  pdf_document: default
---


```{r llama codigos, warning=F, include=T, message=F, echo=FALSE}
library(knitr) # para generar reporte Rmarkdown
library(stringr)
library(reshape) 
library(dplyr) 
library(ggplot2)
library(ggthemes) # para ggplot
library(patchwork) # para unir gráficos de ggplot
library(strucchange) # libreria utilizada para análisis de quiebres

dir.Fig     <-"Figuras/" # carpeta de las figuras utilizadas y generadas en este estudio
fig         <-c("pdf") # formato de figuras generadas por este código
dir.0       <-getwd() # directorio de trabajo 
dir.1       <-paste(dir.0,"/codigos_admb",sep="") # carpeta de códigos ADMB 
dir.fun     <-paste(dir.0,"/funciones/",sep="") # carpeta de funciones utilizadas en este informe
source(paste(dir.fun,"functions.R",sep="")) # funciones para leer .dat y .rep
source(paste(dir.fun,"Fn_PBRs.R",sep="")) # funciones para leer .dat y .rep
ant <-reptoRlist(paste(dir.0,"/DatosEntrada.dat",sep=""))  # datos utilizados para antecedentes

```

```{r CORRE MODELO BASE SEPTIEMBRE, eval=FALSE, echo=FALSE, warning=FALSE, include=F}
setwd(dir.1)
#Asesoría de septiembre
system("~/admb-12.2/admb MAE0920")
system("./MAE0920")
```

```{r CORRE MODELO BASE MARZO, eval=FALSE, echo=FALSE, warning=FALSE,include=F}
setwd(dir.1)
#Asesoría de septiembre
system("~/admb-12.2/admb MAE0321")
system("./MAE0321")
```


```{r  leer datos, echo=FALSE, warning=FALSE, include=T}
setwd(dir.1)

# ASESORÍA DE SEPTIEMBRE
data1        <- lisread("MAE0920.dat") 
names(data1) <- str_trim(names(data1), side="right")
dat1         <- data1
rep1         <- reptoRlist("MAE0920.rep")
std1         <- read.table("MAE0920.std",header=T,sep="",na="NA",fill=T) 

# ASESORÍA DE MARZO
data2        <- lisread("MAE0321.dat") 
names(data2) <- str_trim(names(data2), side="right")
dat2         <- data2
rep2         <- reptoRlist("MAE0321.rep")
std2         <- read.table("MAE0321.std",header=T,sep="",na="NA",fill=T) 
```

```{r Retrospectivo_sept, echo=F, warning=FALSE,eval=F, include=F}
source(paste(dir.fun,"Fn_Retrospectivo.R",sep=""))
Retrospectivo("MAE0920",
              dir.0,
              dir.1,
              "/Retrospectivo_sept",
              system="mac") 
```

```{r Retrospectivo_marzo, echo=F, warning=FALSE,eval=F, include=F}
source(paste(dir.fun,"Fn_Retrospectivo.R",sep=""))
Retrospectivo("MAE0321",
              dir.0,
              dir.1,
              "/Retrospectivo_marz",
              system="mac") 
```

```{r Verosimilitud_sept, echo=F, warning=F,eval=F, include=F}
source(paste(dir.fun,"Fn_Verosimilitud.R",sep=""))
logRo    <- 11.6
factor    <- seq(0.2,2,0.08)
priorRo  <- log(exp(logRo)*factor)

Verosimilitud("MAE0920",
              dir.0,
              dir.1,
              "/Verosimilitud_sept",
              logRo,
              priorRo,
              system="mac") 
```

```{r Verosimilitud_marz, echo=F, warning=F,eval=F, include=F}
source(paste(dir.fun,"Fn_Verosimilitud.R",sep=""))
logRo    <- 11.6
factor    <- seq(0.2,2,0.08)
priorRo  <- log(exp(logRo)*factor)

Verosimilitud("MAE0321",
              dir.0,
              dir.1,
              "/Verosimilitud_marz",
              logRo,
              priorRo,
              system="mac") 
```

```{r PRIMER PASO CBA ASESORIA SEPTIEMBRE, eval=FALSE, echo=FALSE, warning=FALSE, include=F}
source(paste(dir.fun,"Fn_CBA.R",sep=""))
CBA(dir.0,
    dir.1,
    Carpeta="/CBA_sept", #genera carpeta con escenarios de reclutamiento para el cálculo de CBA
    admb="MAE0920", #códigos .dat y .tpl de asesoría de septiembre
    l_opt_proy=323, # línea  de opción de proyección que se debe cambiar
    l_opRec=329,    # línea  de opción de escenario de reclutamiento promedio que se debe cambiar 
    l_opt_wmed=335, # línea de opción de escenario de peso medio que se debe cambiar para la projección
    l_opt_Str=326,  # linea de opción de estrategia de captura 
    l_mf=338,       # línea de opción de multiplicador de F que se puede cambiar
    opt_proy=2,     # Proyecta de un año para otro (CBA inicial, asesoría de septiembre)
    opt_wmed=3,     # peso promedio últimos 5 años de la serie
    opt_Str=1,      # estrategia F constante
    system="mac")   # denpende si estoy en computador de windows o mac
```

```{r PRIMER PASO CBA ASESORIA MARZO, eval=FALSE, echo=FALSE, warning=FALSE, include=F}
source(paste(dir.fun,"Fn_CBA.R",sep=""))
CBA(dir.0,
    dir.1,
    Carpeta="/CBA_marzo", #genera carpeta con escenarios de reclutamiento para el cálculo de CBA
    admb="MAE0321", #códigos .dat y .tpl de asesoría de marzo
    l_opt_proy=330, # línea  de opción de proyección que se debe cambiar
    l_opRec=336,    # línea  de opción de escenario de reclutamiento promedio que se debe cambiar 
    l_opt_wmed=342, # línea de opción de escenario de peso medio que se debe cambiar para la projección
    l_opt_Str=333,  # linea de opción de estrategia de captura 
    l_mf=345,       # línea de opción de multiplicador de F que se puede cambiar
    opt_proy=1,     # IMPORTANTE!! Proyecta para el mismo año (1era y 2da revisión de CBA, asesorías de marzo y julio)
    opt_wmed=3,     # peso promedio últimos 5 años de la serie
    opt_Str=1,      # estrategia F constante
    system="mac")   # denpende si estoy en computador de windows o mac
```


# Antecedentes

```{r Fig2, echo=T,warning=F, include=T, message=F,fig.height=3.5,fig.width=6.5,fig.align="center",fig.path=dir.Fig,dev=fig}
years<-seq(1990,2020,1)
dataDesem  <- ant$des_oficialesvscorregidos
Tdesem  <- data.frame(years,dataDesem[,1:2],rep(median(dataDesem[,2]),length(dataDesem[,2])))
colnames(Tdesem) <- c("Years", 
                      "Desembarques_oficiales", 
                      "Desembarques_oficales_corregidos",
                      "Mediana_desembarques_corregidos")

des_Of_corr <- data.frame(Tdesem) %>% mutate(Registros="desembarques") %>% melt(id.var=c("Years","Registros"))

ggplot(des_Of_corr)+
  geom_line(aes(Years,value/1000,colour=variable))+
  annotate("text", x=2015, y=(round(median(Tdesem[,3]),0)/1000)+15,
  label=paste(round(median(Tdesem[,3]/1000),0),"mil toneladas"))+
  scale_colour_manual(values=c('blue',"black","red")) +
  labs(x = '', y = 'Desembarques (miles de toneladas)',colour="") +
  scale_x_continuous(breaks = seq(from = 1990, to = 2020, by = 2)) +
  theme_bw(base_size=9) + 
  theme(plot.title = element_text(hjust = 0.5),legend.position="top")

```


```{r Fig3, echo=T,warning=F, include=T, message=F,fig.height=3.3,fig.width=6,fig.align="center",fig.path=dir.Fig,dev=fig}
dataDesem2  <- data.frame(ant$year_cuota,ant$des_art,ant$des_ind)
colnames(dataDesem2) <- c("Years", 
                      "Desembarque_artesanal", 
                      "Desembarque_industrial")

dataDesem3  <- data.frame(ant$year_cuota,ant$cuot_art,ant$cuot_ind)
colnames(dataDesem3) <- c("Years",
                      "Cuota_artesanal", 
                      "Cuota_industrial")

des_art_ind <- data.frame(dataDesem2) %>% mutate(Registros="desembarques") %>% melt(id.var=c("Years","Registros"))

cuota_art_ind <- data.frame(dataDesem3) %>% mutate(Registros=c("cuotas")) %>% melt(id.var=c("Years","Registros"))

ggplot(des_art_ind)+
  geom_bar(aes(x=Years, y =value/1000,fill=variable), stat="identity",color = 'gray70') + 
  geom_line(data = cuota_art_ind, aes(x = Years, y = value/1000, colour=variable)) +
  scale_fill_manual(values=c('gray70',"gray50")) +
  scale_color_manual(values=c('black',"red")) +
  labs(x = '', y = 'Miles de toneladas',fill="",color="") +
  scale_x_continuous(breaks = seq(from = 2000, to = 2020, by = 2)) +
  theme_bw(base_size=9) + 
  theme(plot.title = element_text(hjust = 0.5),legend.position="top")
```

```{r Fig4,warning=F, include=T, message=F, echo=T,fig.height=3.3,fig.width=5.8,fig.align="center",fig.path=dir.Fig,dev=fig}
ano<-ant$desembarques_sernapesca[,1]
des_mes<-data.frame(mes=rep(seq(1,12,1),22),ano=gl(22,12,labels=ano),desem=c(t(ant$desembarques_sernapesca[,2:13])))

par(mfcol=c(1,1),mar=c(4,4,1,1))
boxplot(des_mes$desem[145:264]/10^3~des_mes$mes[145:264],las=1,xlab="Mes",
	ylab="Desembarques (miles de t)",col="lightyellow3")
```



```{r Fig7, warning=F, include=T, message=F, echo=T,fig.height=3.5,fig.width=3.5,fig.align="center",fig.path=dir.Fig,dev=fig}

x<-rep1$reclasobs[rep1$reclasobs>0&rep1$pelacesobs>0]/10^6
y<-rep1$pelacesobs[rep1$reclasobs>0&rep1$pelacesobs>0]/10^6
years<-rep1$years

par(mar=c(4,4,1,1))
plot(x,y,las=1,cex=1.5,xlab="Crucero de verano (t.*10^6)",ylab="Crucero de otoño (t.*10^6)",xlim=c(0,5),ylim=c(0,3),cex.lab=0.8,cex.axis=0.8)
text(x,y-0.09,years[rep1$reclasobs>0&rep1$pelacesobs>0],cex=0.7,col=4)

model0<-lm(y~x)
y0<-predict(model0,data.frame(x=seq(0,4,0.1)),interval="prediction",level = 0.98)
lines(seq(0,4,0.1),y0[,1],col=2)
#summary(model0)
text(2,3,paste("Y =",round(model0$coefficients[1],4),"+",round(model0$coefficients[2],3),"X",sep=""),col=4,cex=0.8)
text(2.1,2.8, "R^2=0.00039",col=4,cex=0.8)

```

```{r Fig8,warning=F, include=T, message=F, echo=T,fig.height=3.5,fig.width=6.5,fig.align="center",fig.path=dir.Fig,dev=fig}

anorecl<-ant$reclas_BT_BR_AT_AR[,1]
BTreclas<-ant$reclas_BT_BR_AT_AR[,2]
BRreclas<-ant$reclas_BT_BR_AT_AR[,3]
ATreclas<-ant$reclas_BT_BR_AT_AR[,4]
anopela<-ant$pelaces_BT_AT[,1]
BTpela<-ant$pelaces_BT_AT[,2]
ATpela<-ant$pelaces_BT_AT[,3]

par(mar=c(2,4,1,1)+0.5)
plot(anorecl,BTreclas/1000000,ylim=c(0,5),xaxp=c(2000,2021,21),las=1,ylab="Biomasa acústica (millones de t.)",xlab="",type="o",pch=19,col=1,lwd=2,cex.lab=0.8,cex.axis=0.8)
lines(anorecl,BRreclas/1000000,type="o",pch=19,col=2,lwd=2)
legend(2000,4.5,c("Biomasa Total","Biomasa Reclutas"),pch=19,lwd=2,col=c(1,2),bty="n",cex=0.8)

```



# Metodología

```{r Fig15,  warning=F, include=T, message=F, echo=T,fig.height=3,fig.width=5,fig.align="center",fig.path=dir.Fig,dev=fig}
library(strucchange)
years<-rep2$years
nyears<-length(years)
bp.nile <- breakpoints(rep2$Reclutas ~ 1)
fm0 <- lm(rep2$Reclutas ~ 1)
fm1 <- lm(rep2$Reclutas ~ breakfactor(bp.nile, breaks = 2))
quiebres3<-fitted(fm1)

par(mfrow=c(1,1),mar=c(2,4,1,1))
plot(years,rep2$Reclutas,type="l",lty=2,pch=19,ylim=c(0,700000),
     xaxp=c(1990,2020,30),yaxs="i",xlab="",ylab="Reclutamientos",main="Análisis de quiebres",cex.main=0.8,cex.axis=0.8,cex.lab=0.8)
points(years,rep2$Reclutas,col=1,pch=19)
lines(years,quiebres3,lwd=2,col=4)
text(c(1999,2010,2017),c(fitted(fm1)[1],fitted(fm1)[18],fitted(fm1)[23])+20000,round(c(fitted(fm1)[1],fitted(fm1)[18],fitted(fm1)[23]),0),col=2,font=1,cex=0.8)
```


```{r Fig16,warning=F, include=T, message=F, echo=T,fig.height=4.5,fig.width=9,fig.align="center",fig.path=dir.Fig,dev=fig}
years1<-rep1$years
nyears1<-length(years1)
age   <-seq(0,4,1)                                            
nage  <-length(age)
pobsF <-rep1$pf_obs 
  
#Proporcion observada                                        
WmedF <-dat1$Wmed                                             
WiniF <-dat1$Wini                                 
#Proporciones                                                
Wm    <-c(WmedF); Wm[Wm==0]  <-NA                     
Wi    <-c(WiniF); Wi[Wi==0]  <-NA 

x1 <-c(years1[1],years1[nyears1]+1,nyears1+1/2)
#Proporci?n de edad
par(mar=c(4,4,2,1),mfrow=c(1,2))
# pesos medios
plot(years1,WmedF[,1],type="n",las=1,ylim=c(0,70),xlim=c(1990,years1[nyears1]),ylab="Pesos medios (grs)",xlab="",xaxp=x1,main="")
for(i in 1:5){
lines(years1,WmedF[,i],col=i,type="o", pch=19)}
legend(1990,71,c("edad 0","edad 1","edad 2","edad 3","edad 4"),pch=19,lwd=1,col=1:5,bty="n")


plot(age,colMeans(WmedF),type="o",pch=19,ylab="Pesos medios (grs)",xlab="Edad (años)")
lines(age,colMeans(WmedF[nyears1-5:nyears1,]),col=2,type="o",pch=19)
legend(0,37,c("peso medio histórico","peso medio últimos 5 años"),pch=19,lwd=1,col=c(1,2),bty="n")
```

# Resultados


```{r Fig19, warning=F, include=T, message=F, echo=T,fig.height=4.5,fig.width=8,fig.align="center",fig.path=dir.Fig,dev=fig}
setwd(dir.1)
years  <- rep2$years 
nyears <- dat2$nanos                                                                
x2      <-c(years,rev(years))
x1_2    <-c(years[1],years[nyears]+1,nyears+1/2) #xaxp
x2_2    <-c(years[1]-1,years[nyears]+1) #xlim

ydesembarques<-rep2$years[rep2$desembarqueobs>0]
yreclas      <-rep2$years[rep2$reclasobs>0]
ypelaces     <-rep2$years[rep2$pelacesobs>0]
ycompflota   <-rep2$years[rowSums(rep2$pf_obs)>0]
ycompreclas  <-rep2$years[rowSums(rep2$pobs_RECLAS)>0]
ycomppelaces <-rep2$years[rowSums(rep2$pobs_PELACES)>0]
ypesomedio   <-rep2$years[rowSums(dat2$Wmed)>0]
ypesoinicial <-rep2$years[rowSums(dat2$Wini)>0]

par(mfrow=c(1,1),mar=c(2,2,1,1)+0.5)
plot(years,rep(0,length(years)),type="n",ylim=c(0,9),ylab="",xlab="",xaxp=x1_2,axes=F,xlim=c(1991,2027.5))
abline(v=2022)
points(ydesembarques,rep(1,length(ydesembarques)),lwd=15,col=1)
points(yreclas,rep(2,length(yreclas)),lwd=15,col=2)
points(ypelaces,rep(3,length(ypelaces)),lwd=15,col=3)
points(ycompflota,rep(4,length(ycompflota)),lwd=15,col=4)
points(ycompreclas,rep(5,length(ycompreclas)),lwd=15,col=5)
points(ycomppelaces,rep(6,length(ycomppelaces)),lwd=15,col=6)
points(ypesomedio,rep(7,length(ypesomedio)),lwd=15,col=7)
points(ypesoinicial,rep(8,length(ypesoinicial)),lwd=15,col=8)

ejey<-c("Desembarques","Biom_Cru_verano","Biom_Cru_otoño","CompEdad Flota","CompEdad C.verano","CompEdad C.otoño","Peso medio Flota","Peso inicial Flota")

#legend()
axis(1,years,xaxp=x1_2)
text(rep(2025.5,8),1:8,ejey,cex=0.8)

box()
```

```{r Fig20, warning=F, include=T, message=F, echo=T,fig.height=8,fig.width=5,fig.align="center",fig.path=dir.Fig,dev=fig}
 
des_obs <- data.frame(rep2$desembarqueobs)
bc_obs  <- data.frame(rep2$reclasobs)
bp_obs  <- data.frame(rep2$pelacesobs)
yearc   <- rep2$years 
nyearc  <-length(yearc)  

 obsC  <- as.data.frame(bc_obs) %>% mutate(year=yearc) %>% melt(id.vars='year') %>% mutate(type='2.Cruceros de Verano')
 obsP  <- as.data.frame(bp_obs) %>% mutate(year=yearc) %>% melt(id.vars='year') %>% mutate(type='3.Cruceros de Otoño')
 obsD  <- as.data.frame(des_obs) %>% mutate(year=yearc) %>% melt(id.vars='year') %>% mutate(type='1.Desembarques')
 Bcru  <-rbind(obsC,obsP,obsD)

p <- ggplot()  +
  geom_bar(data=Bcru, aes(x=year, y =value), stat="identity", fill='gray66', 
                   color = 'gray28') + 
    facet_wrap(~type,scale="free",dir = 'v', as.table = TRUE) + labs(x="Años", y="Toneladas")
p +  theme(panel.background = element_rect(fill ="gray99")) + theme(panel.grid=element_line(color="gray66"))


```

```{r Fig21, warning=F, include=T, message=F,eval=T, echo=T,fig.height=4,fig.width=9,fig.align="center",fig.path=dir.Fig,dev=fig}

years    <- rep2$years 
nyears   <- length(years)
age      <- seq(0,4,1)                                            
nage     <- length(age)
WmedF    <- dat2$Wmed                                             
WiniF    <- dat2$Wini    
pobsF    <- rep2$pf_obs                                              

WmedF <- as.data.frame(WmedF) %>% mutate(years=years) %>% melt(id.vars='years') %>%             mutate(edad = rep(age, each=nyears)) %>% mutate(type='WmedF')

pobsF <- as.data.frame(pobsF) %>% mutate(years=years) %>% melt(id.vars='years') %>%             mutate(edad = rep(age, each=nyears)) %>% mutate(type='pobsF')


f1<-ggplot(pobsF, aes(x = years, y = value, group=edad,colour=edad))+
  geom_line() +
  geom_point( size=2, shape=21, fill="white") + 
  labs(x = '', y = 'Proporción de captura en N° a la edad',fill="",color=" grupos de edad") +
  scale_x_continuous(breaks = seq(from = 1990, to = 2020, by = 5)) +
  ggtitle("FLOTA")+
  theme_bw(base_size=11) + 
  theme(plot.title = element_text(hjust = 0.5),legend.position="none")

f2<-ggplot(WmedF, aes(x = years, y = value, group=edad,colour=edad))+
  geom_line() +
  geom_point( size=2, shape=21, fill="white") + 
  labs(x = '', y = 'Pesos medios (grs)',fill="",color=" grupos de edad") +
  scale_x_continuous(breaks = seq(from = 1990, to = 2020, by = 5)) +
   ggtitle("FLOTA")+
  theme_bw(base_size=11) + 
  theme(plot.title = element_text(hjust = 0.5))

f1 + f2

```


```{r Fig22,warning=F, include=T, message=F, echo=T,fig.height=6,fig.width=9,fig.align="center",fig.path=dir.Fig,dev=fig}
pobsF    <- rep2$pf_obs      
pF   <- c(pobsF); pF[pF==0]  <-NA
WmedF    <- dat2$Wmed    
Wm   <- c(WmedF); Wm[Wm==0]  <-NA     

years    <- rep2$years 
nyears   <- dat2$nanos
age      <- seq(0,4,1)                                            
nage     <- length(age)

anos <- rep(years,length(age)) 
edad <- gl((length(age)),length(years),label=age)   

datosProp=data.frame(x=edad,y=anos,tamanio=pF)
datosWmed=data.frame(x=edad,y=anos,tamanio=Wm )

g1 <- ggplot (datosProp,aes(x,y)) +
     geom_point(aes(size=tamanio),color = 'gray25',shape=21, fill="gray85",alpha = 0.7) +
     scale_size_continuous(breaks = seq(0.05,0.65,0.2),range=c(0,6))+
     labs(x = 'Edades', y = 'Años',size="Proporción") +
     ggtitle("Proporción de edad de la Flota")+
     theme_bw(base_size=11) + 
     theme(plot.title = element_text(hjust = 0.5))

g2 <- ggplot (datosWmed,aes(x,y)) + 
      geom_point(aes(size=tamanio),color = 'gray25',shape=21, fill="gray85",alpha=0.7) +
      scale_size_continuous(breaks = seq(15,75,20),range=c(0,6))+
      labs(x = 'Edades', y = 'Años',size="Gramos") +
      ggtitle("Pesos medios de la Flota")+
      theme_bw(base_size=11) + 
      theme(plot.title = element_text(hjust = 0.5))

g1 + g2

```


```{r Fig23, warning=F, include=T, message=F, echo=T,fig.height=4,fig.width=9,fig.align="center",fig.path=dir.Fig,dev=fig}

years    <- rep2$years 
nyears   <- dat2$nanos
age      <- seq(0,4,1)                                            
nage     <- length(age)
pobsR    <- rep2$pobs_RECLAS                                               
pobsP    <- rep2$pobs_PELACES 


pobsR <- as.data.frame(pobsR) %>% mutate(years=years) %>% melt(id.vars='years') %>%             mutate(edad = rep(age, each=nyears)) %>% mutate(type='pobsR')

pobsP <- as.data.frame(pobsP) %>% mutate(years=years) %>% melt(id.vars='years') %>%             mutate(edad = rep(age, each=nyears)) %>% mutate(type='pobsP')


f1<-ggplot(pobsR, aes(x = years, y = value, group=edad,colour=edad))+
  geom_line() +
  geom_point( size=2, shape=21, fill="white") + 
  labs(x = '', y = 'Proporción de captura en N° a la edad',fill="",color=" grupos de edad") +
  scale_x_continuous(breaks = seq(from = 1990, to = 2020, by = 5)) +
  ggtitle("CRUCERO DE VERANO")+
  theme_bw(base_size=11) + 
  theme(plot.title = element_text(hjust = 0.5),legend.position="none")

f2<-ggplot(pobsP, aes(x = years, y = value, group=edad,colour=edad))+
  geom_line() +
  geom_point( size=2, shape=21, fill="white") + 
  labs(x = '', y = 'Proporción de captura en N° a la edad',fill="",color=" grupos de edad") +
  scale_x_continuous(breaks = seq(from = 1990, to = 2020, by = 5)) +
  ggtitle("CRUCERO DE OTOÑO")+
  theme_bw(base_size=11) + 
  theme(plot.title = element_text(hjust = 0.5))

f1 + f2

```


```{r Fig24,warning=F, include=T, message=F, echo=T,fig.height=6,fig.width=9,fig.align="center",fig.path=dir.Fig,dev=fig}
pobsR    <- rep2$pobs_RECLAS        
pR       <- c(pobsR); pR[pR==0]  <-NA
pobsP    <- rep2$pobs_PELACES      
pP       <- c(pobsP); pP[pP==0]  <-NA 

years    <- rep2$years 
nyears   <- dat2$nanos
age      <- seq(0,4,1)                                            
nage     <- length(age)

anos <- rep(years,length(age)) 
edad <- gl((length(age)),length(years),label=age)   

datosPropR=data.frame(x=edad,y=anos,tamanio=pR)
datosPropP=data.frame(x=edad,y=anos,tamanio=pP )

g1 <- ggplot (datosPropR,aes(x,y)) +
     geom_point(aes(size=tamanio),color = 'gray25',shape=21, fill="gray85",alpha = 0.7) +
     scale_size_continuous(breaks = seq(0.05,0.65,0.2),range=c(0,6))+
     labs(x = 'Edades', y = 'Años',size="Proporción") +
     ggtitle("Cruceros de Verano")+
     theme_bw(base_size=11) + 
     theme(plot.title = element_text(hjust = 0.5))

g2 <- ggplot (datosPropP,aes(x,y)) + 
      geom_point(aes(size=tamanio),color = 'gray25',shape=21, fill="gray85",alpha=0.7) +
      scale_size_continuous(breaks = seq(0.05,0.65,0.2),range=c(0,6))+
      labs(x = 'Edades', y = 'Años',size="Proporción") +
      ggtitle("Cruceros de otoño")+
      theme_bw(base_size=11) + 
      theme(plot.title = element_text(hjust = 0.5))

g1 + g2

```

# Ajuste del modelo a los datos

```{r Fig26,warning=F, include=T, message=F, echo=T,fig.height=6.7,fig.width=6.5,fig.align="center",fig.path=dir.Fig,dev=fig}

yrs   <- rep2$years
nyrs  <- length(yrs)
lasty <- yrs[nyrs]
cvBcV   <-0.30
cvBcO   <-0.30
cvdes   <-0.01

ind_obs           <- cbind(c(rep2$reclasobs),c(rep2$pelacesobs), c(rep2$desembarqueobs)); ind_obs[ind_obs==0] <- NA
colnames(ind_obs) <- c('Crucero_verano', 'Crucero_otoño', 'Desembarques') 
ind               <- data.frame(ind_obs) %>% mutate(Asesoria='observado') %>% mutate (yrs= yrs) %>% melt(id.var=c('yrs', 'Asesoria'))  
     

ind_sept           <- cbind(c(rep1$reclaspred,NA), c(rep1$pelacespred,NA), c(rep1$desembarquepred,NA)) 
colnames(ind_sept) <- c('Crucero_verano', 'Crucero_otoño', 'Desembarques') 

ind_marzo           <- cbind(c(rep2$reclaspred), c(rep2$pelacespred), c(rep2$desembarquepred)) 
colnames(ind_marzo) <- c('Crucero_verano', 'Crucero_otoño', 'Desembarques') 

sept               <- data.frame(ind_sept) %>% mutate (Asesoria='septiembre_2020') %>% mutate (yrs= yrs)  %>% melt(id.var=c('yrs', 'Asesoria'))

marzo              <- data.frame(ind_marzo) %>% mutate (Asesoria='marzo_2021') %>% mutate (yrs= yrs)  %>% melt(id.var=c('yrs', 'Asesoria'))

base1 <- data.frame(rbind(ind, sept,marzo))  


BcV <- ggplot(base1 %>% filter(Asesoria!='observado', variable=='Crucero_verano'), 
       aes(yrs,value/1000000)) + 
       geom_line(aes(colour=Asesoria), size=0.8) +
       scale_colour_manual(values=c('red','black')) +
       geom_point(data = base1 %>% filter(Asesoria=='observado', variable=='Crucero_verano'),
       aes(yrs,value/1000000), shape = 19, colour = 'gray30') +
       geom_errorbar(data = base1 %>% filter(Asesoria=='observado', variable=='Crucero_verano'),
       aes(ymin = value*exp(-1.96*cvBcO)*10^-6, ymax = value*exp(1.96*cvBcO)*10^-6), color = 'gray30') +
       scale_x_continuous(breaks = seq(from = 1985, to = 2021, by = 5)) +
       labs(x = '', y = 'Toneladas (millones)') +
       theme_bw(base_size=9) + 
       ggtitle('Crucero de verano')+
       theme(plot.title = element_text(hjust = 0.5),legend.position="none")

BcP <- ggplot(base1 %>% filter(Asesoria!='observado', variable=='Crucero_otoño'), 
       aes(yrs,value/1000000)) + 
       geom_line(aes(colour=Asesoria), size=0.8) +
       scale_colour_manual(values=c('red','black'),name="Asesorías") +
       geom_point(data = base1 %>% filter(Asesoria=='observado', variable=='Crucero_otoño'),
       aes(yrs,value/1000000), shape = 19, colour = 'gray30') +
       geom_errorbar(data = base1 %>% filter(Asesoria=='observado', variable=='Crucero_otoño'),
       aes(ymin = value*exp(-1.96*cvBcV)*10^-6, ymax = value*exp(1.96*cvBcV)*10^-6), color = 'gray30') +
       scale_x_continuous(breaks = seq(from = 1985, to = 2021, by = 5)) +
       labs(x = '', y = 'Toneladas (millones)') +
       theme_bw(base_size=9) + 
       ggtitle('Crucero de otoño')+
       theme(plot.title = element_text(hjust = 0.5))

d   <- ggplot(base1 %>% filter(Asesoria!='observado', variable=='Desembarques'), 
       aes(yrs,value/1000)) +
       geom_line(aes(colour=Asesoria), size=0.8) +
       scale_colour_manual(values=c('red','black')) +
       geom_point(data = base1 %>% filter(Asesoria=='observado', variable=='Desembarques'),
       aes(yrs,value/1000), shape = 19, colour = 'gray30') +
       geom_errorbar(data = base1 %>% filter(Asesoria=='observado', variable=='Desembarques'),
       aes(ymin = value*exp(-1.96*cvdes)*10^-3, ymax = value*exp(1.96*cvdes)*10^-3), color = 'gray30') +
       scale_x_continuous(breaks = seq(from = 1985, to = 2021, by = 5)) +
       labs(x = '', y = 'Toneladas (miles)') +
       theme_bw(base_size=9) + 
       ggtitle('Desembarques') +
       theme(plot.title = element_text(hjust = 0.5),legend.position="none")

BcV/BcP/d + plot_layout(guides="collect")

```


```{r datos_ajustes, echo=T }

# I. INDICES DE ABUNDANCIA                                                       #
years  <- dat2$Ind[,1]                                                              
nyears <- dat2$nanos                                                                
age    <- seq(0,4,1)                    
nage   <- dat2$nedades                                                            
Amax   <- dat2$nedades        
Age    <- seq(0,4,1) 
#Observado                                                                      
obsR <- rep2$reclasobs       ;obsR[obsR<=1] <-NA                                 
obsP <- rep2$pelacesobs      ;obsP[obsP<=1] <-NA                                 
obsM <- rep2$mphobs          ;obsM[obsM<=1] <-NA                                 
obsD <- rep2$desembarqueobs                                                      
#predicho                   #stdpredicho                                        
predR <- rep2$reclaspred             
predP <- rep2$pelacespred              
predM <- rep2$mphpred                         
predD <- rep2$desembarquepred                                                    
#Residuos                                                                       
Res_reclas   <-log(obsR)-log(predR)                                             
Res_Pelaces  <-log(obsP)-log(predP)                                             
Res_MPH      <-log(obsM)-log(predM)                                             
Res_Desemb   <-log(obsD)-log(predD)     

x  <-c(years,rev(years))
x1 <-c(years[1],years[nyears]+1,nyears+1/2) #xaxp
x2 <-c(years[1]-1,years[nyears]+1) #xlim

cvreclas<-rep(0.30,nyears)
cvpela<-rep(0.30,nyears)
cvdes<-rep(0.01,nyears)

obsR95i <- obsR*exp(-1.96*cvreclas);obsR95s <-obsR*exp(1.96*cvreclas)
obsP95i <- obsP*exp(-1.96*cvpela);obsP95s <-obsP*exp(1.96*cvpela)
obsD95i <- obsD*exp(-1.96*cvdes);obsD95s <-obsD*exp(1.96*cvdes)
```

```{r Fig27, warning=F, include=T, message=F, echo=T,fig.height=7,fig.width=9,fig.align="center",fig.path=dir.Fig,dev=fig}
par(mfcol=c(3,3),mar=c(2,4,1,1)+0.5)

 plot(years,Res_reclas,xaxp=x1,cex.axis=0.8,ylim=c(-1.1,1.1),type="h",main="Cruceros de Verano",ylab="Residuales (escala log)",xlab="")
	#mtext("b)",side=3,line=0.25,adj=-0.15,cex=1.5)
	abline(h=0,col="darkgray")
	plot(log(predR),Res_reclas, ylim=c(-1.1,1.1),main="Residuales vs ajustado",ylab="Residuales",xlab="Valor ajustado")
	abline(h=0,col="darkgray")
	#hist(Res_reclas,xlab="Residuales",ylab="Frecuencia",main="Histograma de Residuos")
	qqnorm(Res_reclas,ylim=c(-1.1,1.1)); qqline(Res_reclas, col = 2)
	
	plot(years,Res_Pelaces,xaxp=x1,ylim=c(-1.1,1.1),cex.axis=0.8,type="h",main="Cruceros de Otoño",ylab="Residuales (escala log)",xlab="")
	#mtext("b)",side=3,line=0.25,adj=-0.15,cex=1.5)
	abline(h=0,col="darkgray")
	plot(log(predP),Res_Pelaces,ylim=c(-1.1,1.1), main="Residuales vs ajustado",ylab="Residuales",xlab="Valor ajustado")
	abline(h=0,col="darkgray")
	#hist(Res_Pelaces,xlab="Residuales",ylab="Frecuencia",main="Histograma de Residuos")
	qqnorm(Res_Pelaces,ylim=c(-1.1,1.1)); qqline(Res_Pelaces, col = 2)
	
  plot(years,Res_Desemb,xaxp=x1,cex.axis=0.8,ylim=c(-1.1,1.1),type="h",main="Desembarques",ylab="Residuales (escala log)",xlab="")
#	mtext("b)",side=3,line=0.25,adj=-0.15,cex=1.5)
	abline(h=0,col="darkgray")
	plot(log(predD),Res_Desemb, ylim=c(-1.1,1.1),main="Residuales vs ajustado",ylab="Residuales",xlab="Valor ajustado")
	abline(h=0,col="darkgray")
	#hist(Res_Desemb,xlab="Residuales",ylab="Frecuencia",main="Histograma de Residuos")
	qqnorm(Res_Desemb,ylim=c(-1.1,1.1)); qqline(Res_Desemb, col = 2)
	
```



```{r Fig28,warning=F, include=T, message=F, echo=T,fig.height=7,fig.width=8,fig.align="center",fig.path=dir.Fig,dev=fig}

years   <- dat2$Ind[,1] 
nyears  <- length(years)  
age  <-seq(0,4,1)                                            
nage<-length(age)   

etcf1_obs <- data.frame(rep2$pf_obs)
etcf1_pre <- rbind(rep1$pf_pred,rep(NA,nage)) 
etcf2_pre <- rep2$pf_pred 

 obs  <- as.data.frame(etcf1_obs) %>% mutate(year=years) %>% melt(id.vars='year') %>%
              mutate(edad = rep(age, each=nyears)) %>% mutate(type='obs')
 
 pred_sep <- as.data.frame(etcf1_pre) %>% mutate(year=years) %>% melt(id.vars='year') %>%
              mutate(edad = rep(age, each=nyears)) %>% mutate(type='septiembre_2020')
 
 pred_marzo <- as.data.frame(etcf2_pre) %>% mutate(year=years) %>% melt(id.vars='year') %>%
              mutate(edad = rep(age, each=nyears)) %>% mutate(type='marzo_2021')
  
  mat  <- rbind(obs,pred_sep,pred_marzo)
 
  fig1 <- ggplot(filter(mat, type=='obs')) + 
          geom_bar(aes(x = edad, y = value), stat="identity", fill='gray66', color = 'gray28') + 
          facet_wrap(~year, dir = 'v', as.table = TRUE) + labs(x = 'Edad', y = 'Proporción') +
          geom_line(data = mat %>% filter(type != 'obs'), aes(x = edad, y = value, colour=type)) +
          scale_colour_manual(values=c('red','black'),name="Asesorías") +
          theme(panel.background = element_rect(fill ="gray99")) + theme(panel.grid=element_line(color=NA)) +
          ggtitle("FLOTA") + theme(plot.title = element_text(size = 12))
  fig1
  
```


```{r Fig29,warning=F, include=T, message=F, echo=T,fig.height=7,fig.width=8,fig.align="center",fig.path=dir.Fig,dev=fig}

years   <- dat2$Ind[,1] 
nyears  <- length(years)  
age  <-seq(0,4,1)                                            
nage<-length(age)   

etcf1_obs <- data.frame(rep2$pobs_RECLAS)
etcf1_pre <- rbind(rep1$ppred_RECLAS,rep(NA,nage)) 
etcf2_pre <- rep2$ppred_RECLAS

 obs  <- as.data.frame(etcf1_obs) %>% mutate(year=years) %>% melt(id.vars='year') %>%
              mutate(edad = rep(age, each=nyears)) %>% mutate(type='obs')
 
 pred_sep <- as.data.frame(etcf1_pre) %>% mutate(year=years) %>% melt(id.vars='year') %>%
              mutate(edad = rep(age, each=nyears)) %>% mutate(type='septiembre_2020')
 
 pred_marzo <- as.data.frame(etcf2_pre) %>% mutate(year=years) %>% melt(id.vars='year') %>%
              mutate(edad = rep(age, each=nyears)) %>% mutate(type='marzo_2021')
  
  mat  <- rbind(obs,pred_sep,pred_marzo)
 
  fig1 <- ggplot(filter(mat, type=='obs')) + 
          geom_bar(aes(x = edad, y = value), stat="identity", fill='gray66', color = 'gray28') + 
          facet_wrap(~year, dir = 'v', as.table = TRUE) + labs(x = 'Edad', y = 'Proporción') +
          geom_line(data = mat %>% filter(type != 'obs'), aes(x = edad, y = value, colour=type)) +
          scale_colour_manual(values=c('red','black'),name="Asesorías") +
          theme(panel.background = element_rect(fill ="gray99")) + theme(panel.grid=element_line(color=NA)) +
          ggtitle("CRUCEROS DE VERANO") + theme(plot.title = element_text(size = 12))
  fig1
  
```


```{r Fig30,warning=F, include=T, message=F, echo=T,fig.height=7,fig.width=8,fig.align="center",fig.path=dir.Fig,dev=fig}

years   <- dat2$Ind[,1] 
nyears  <- length(years)  
age  <-seq(0,4,1)                                            
nage<-length(age)   

etcf1_obs <- data.frame(rep2$pobs_PELACES)
etcf1_pre <- rbind(rep1$ppred_PELACES,rep(NA,nage)) 
etcf2_pre <- rep2$ppred_PELACES

 obs  <- as.data.frame(etcf1_obs) %>% mutate(year=years) %>% melt(id.vars='year') %>%
              mutate(edad = rep(age, each=nyears)) %>% mutate(type='obs')
 
 pred_sep <- as.data.frame(etcf1_pre) %>% mutate(year=years) %>% melt(id.vars='year') %>%
              mutate(edad = rep(age, each=nyears)) %>% mutate(type='septiembre_2020')
 
 pred_marzo <- as.data.frame(etcf2_pre) %>% mutate(year=years) %>% melt(id.vars='year') %>%
              mutate(edad = rep(age, each=nyears)) %>% mutate(type='marzo_2021')
  
  mat  <- rbind(obs,pred_sep,pred_marzo)
 
  fig1 <- ggplot(filter(mat, type=='obs')) + 
          geom_bar(aes(x = edad, y = value), stat="identity", fill='gray66', color = 'gray28') + 
          facet_wrap(~year, dir = 'v', as.table = TRUE) + labs(x = 'Edad', y = 'Proporción') +
          geom_line(data = mat %>% filter(type != 'obs'), aes(x = edad, y = value, colour=type)) +
          scale_colour_manual(values=c('red','black'),name="Asesorías") +
          theme(panel.background = element_rect(fill ="gray99")) + theme(panel.grid=element_line(color=NA)) +
          ggtitle("CRUCEROS DE OTOÑO") + theme(plot.title = element_text(size = 12))
  fig1
  
```


```{r Fig31, echo=T, warning=F, include=T, message=F,fig.height=5,fig.width=10,fig.align="center",fig.path=dir.Fig,dev=fig}

ppredF<-rep2$pf_pred                                          
ppredR<-rep2$ppred_RECLAS                                     
ppredP<-rep2$ppred_PELACES

#DESEMBARQUES
anos<-dat2$Ind[,1] 
obsF <-pobsF
preF <-ppredF  
resF <-obsF-preF

rng <-range(resF,na.rm=T)
dd  <-dim(resF)
est <-matrix(NA,nrow=dd[1],ncol=dd[2])

for(j in 1:dd[1]){for(k in 1:dd[2]){val<-resF[j,k]
if(val>0){est[j,k]<-val/rng[2]}
else{est[j,k]<-val/rng[1]*-1}}}

par(mfrow=c(1,3),mar=c(5.4,6.7,2,1),cex.axis=1,cex.lab=1.1)
image(age,anos,t(est),col=0,yaxt="n",xlab="",ylab="")
ee  <-dim(est)
for(n in 1:ee[1]){for(m in 1:ee[2]){vol<-est[n,m]
if(is.na(vol)==FALSE){
	if(vol>0){points(age[m],anos[n],pch=19,cex=2.82*sqrt(vol),col=1)}
	if(vol<0){points(age[m],anos[n],pch=1,cex=2.82*sqrt(vol*-1),col=1)}
}}}

mtext("Flota",side=3,cex=1.2)
mtext("Edades",side=1,line=3.2,cex=1.1);posi<-seq(1,57,by=4)
axis(2,at=anos,labels=anos,las=2)
mtext("Años",side=2,line=4.7,cex=1.1)
	mtext("a)",side=3,line=0.25,adj=-0.15,cex=1.5)
box()

# RECLAS
anos<-years[11:nyears]
obsR <-pobsR[11:nyears,]
preR <-ppredR[11:nyears,]
resR <-obsR-preR

rng <-range(resR,na.rm=T)
dd  <-dim(resR)
est <-matrix(NA,nrow=dd[1],ncol=dd[2])

for(j in 1:dd[1]){for(k in 1:dd[2]){val<-resR[j,k]
if(val>0){est[j,k]<-val/rng[2]}
else{est[j,k]<-val/rng[1]*-1}}}

#par(mar=c(5.4,6.7,2,1),cex.axis=1,cex.lab=1.1)
image(age,anos,t(est),col=0,yaxt="n",xlab="",ylab="")
ee  <-dim(est)
for(n in 1:ee[1]){for(m in 1:ee[2]){vol<-est[n,m]
if(is.na(vol)==FALSE){
	if(vol>0){points(age[m],anos[n],pch=19,cex=2.82*sqrt(vol),col=1)}
	if(vol<0){points(age[m],anos[n],pch=1,cex=2.82*sqrt(vol*-1),col=1)}
}}}
mtext("Crucero de verano",side=3,cex=1.2)
mtext("Edades",side=1,line=3.2,cex=1.1);posi<-seq(1,57,by=4)
axis(2,at=anos,labels=anos,las=2)
mtext("Años",side=2,line=4.7,cex=1.1)
mtext("b)",side=3,line=0.25,adj=-0.15,cex=1.5)
box()

# PELACES
anos<-years[17:nyears]
obsP <-pobsP[17:nyears,]
preP <-ppredP[17:nyears,]  
resP <-obsP-preP

rng <-range(resP,na.rm=T)
dd  <-dim(resP)
est <-matrix(NA,nrow=dd[1],ncol=dd[2])

for(j in 1:dd[1]){for(k in 1:dd[2]){val<-resP[j,k]
if(val>0){est[j,k]<-val/rng[2]}
else{est[j,k]<-val/rng[1]*-1}}}

#par(mar=c(5.4,6.7,2,1),cex.axis=1,cex.lab=1.1)
image(age,anos,t(est),col=0,yaxt="n",xlab="",ylab="")
ee  <-dim(est)
for(n in 1:ee[1]){for(m in 1:ee[2]){vol<-est[n,m]
if(is.na(vol)==FALSE){
	if(vol>0){points(age[m],anos[n],pch=19,cex=2.82*sqrt(vol),col=1)}
	if(vol<0){points(age[m],anos[n],pch=1,cex=2.82*sqrt(vol*-1),col=1)}
}}}
mtext("Crucero de otoño",side=3,cex=1.2)
mtext("Edades",side=1,line=3.2,cex=1.1);posi<-seq(1,57,by=4)
axis(2,at=anos,labels=anos,las=2)
mtext("Años",side=2,line=4.7,cex=1.1)
mtext("c)",side=3,line=0.25,adj=-0.15,cex=1.5)
box()

```


```{r VariablesMarzo_std, echo=T,message=FALSE, warning=FALSE, include=T}

years<-rep2$years
nyears<-length(years)

Rt2      <- subset(std2,name=="Reclutas")$value 
Rt2std   <- subset(std2,name=="Reclutas")$std
BT2      <- subset(std2,name=="BT")$value   
BT2std   <- subset(std2,name=="BT")$std
BD2      <- subset(std2,name=="SSB")$value   
BD2std   <- subset(std2,name=="SSB")$std
Ft2      <- subset(std2,name=="log_Ft")$value   
Ft2std   <- subset(std2,name=="log_Ft")$std

VarPob<- data.frame(x=years, Rt2=Rt2,BT2=BT2,BD2=BD2,Ft2=exp(Ft2), 
         lowerRt2 = (Rt2 -1.96*Rt2std), upperRt2 = (Rt2+1.96*Rt2std),
         lowerBT2 = (BT2 -1.96*BT2std), upperBT2 = (BT2+1.96*BT2std),
         lowerBD2 = (BD2 -1.96*BD2std), upperBD2 = (BD2+1.96*BD2std),
         lowerFt2 = exp(Ft2 -1.96*Ft2std), upperFt2 = exp(Ft2+1.96*Ft2std))

```

```{r Fig32_data, eval=T, warning=F, include=T, message=F, echo=T,fig.height=7,fig.width=4,fig.align="center",fig.path=dir.Fig,dev=fig}

dir<-paste(dir.0,"/rep_AsesoriasPrevias",sep="")
setwd(dir)

sept18 <-paste(dir,"/MAE0918.rep",sep="")
mar19  <-paste(dir,"/MAE0319.rep",sep="")
jul19  <-paste(dir,"/MAE0719.rep",sep="")
sept19 <-paste(dir,"/MAE0919.rep",sep="")
mar20  <-paste(dir,"/MAE0320.rep",sep="")
jul20  <-paste(dir,"/MAE0720.rep",sep="")
sept20 <-paste(dir,"/MAE0920.rep",sep="")
mar21  <-paste(dir.1,"/MAE0321.rep",sep="")

#================================================================================#
rep_sept18 <- reptoRlist(sept18)
rep_mar19  <- reptoRlist(mar19)
rep_jul19  <- reptoRlist(jul19)
rep_sept19 <- reptoRlist(sept19)
rep_mar20 <- reptoRlist(mar20)
rep_jul20 <- reptoRlist(jul20)
rep_sept20 <- reptoRlist(sept20)
rep_mar21  <- reptoRlist(mar21)
#================================================================================#
years  <- rep_mar21$years
nyears <- length(years)                                                                
x  <-c(years,rev(years))
x1 <-c(years[1],years[nyears]+1,nyears+1/2) #xaxp
x2 <-c(years[1]-1,years[nyears]+1) #xlim

 Rtcomp <- data.frame(x=years,
                          Rt_sept18=c(rep_sept18$Reclutas,NA,NA,NA),
                          Rt_mar19=c(rep_mar19$Reclutas,NA,NA),
                          Rt_jul19=c(rep_jul19$Reclutas,NA,NA),
                          Rt_sept19=c(rep_sept19$Reclutas,NA,NA),
                          Rt_mar20=c(rep_mar20$Reclutas,NA),
                          Rt_jul20=c(rep_jul20$Reclutas,NA),
                          Rt_sept20=c(rep_sept20$Reclutas,NA),
                          Rt_mar21=c(rep_mar21$Reclutas))
 SSBtcomp <- data.frame(x=years,
                          SSBt_sept18=c(rep_sept18$SSB,NA,NA,NA),
                          SSBt_mar19=c(rep_mar19$SSB,NA,NA),
                          SSBt_jul19=c(rep_jul19$SSB,NA,NA),
                          SSBt_sept19=c(rep_sept19$SSB,NA,NA),
                          SSBt_mar20=c(rep_mar20$SSB,NA),
                          SSBt_jul20=c(rep_jul20$SSB,NA),
                          SSBt_sept20=c(rep_sept20$SSB,NA),
                          SSBt_mar21=c(rep_mar21$SSB))
 
 Ftcomp <- data.frame(x=years,
                          Ft_sept18=c(rep_sept18$Ftot,NA,NA,NA),
                          Ft_mar19=c(rep_mar19$Ftot,NA,NA),
                          Ft_jul19=c(rep_jul19$Ftot,NA,NA),
                          Ft_sept19=c(rep_sept19$Ftot,NA,NA),
                          Ft_mar20=c(rep_mar20$Ftot,NA),
                          Ft_jul20=c(rep_jul20$Ftot,NA),
                          Ft_sept20=c(rep_sept20$Ftot,NA),
                          Ft_mar21=c(rep_mar21$Ftot))
  
  
```


```{r Fig32, echo=T, message=FALSE, warning=FALSE, include=T, fig.align="center", fig.height=7, fig.width=7,fig.path=dir.Fig,dev=fig}

year_retros <- c("2021_marzo","2020_sept","2020_julio","2020_marzo","2019_sept")
nretros <-5


#Retrospectivo tradicional
Rt <- ggplot(Rtcomp) + 
    geom_ribbon(data=VarPob,aes(ymin=lowerRt2, ymax=upperRt2, x=x, fill = "IC"), alpha = 0.2)+
    geom_line(aes(y=Rt_sept19, x=x, colour = year_retros[nretros]), size=0.5)+
    geom_line(aes(y=Rt_mar20, x=x, colour = year_retros[nretros-1]), size=0.5)+
    geom_line(aes(y=Rt_jul20, x=x, colour = year_retros[nretros-2]), size=0.5)+
    geom_line(aes(y=Rt_sept20, x=x, colour = year_retros[nretros-3]), size=0.5)+
    geom_line(aes(y=Rt_mar21, x=x, colour = year_retros[nretros-4]), size=0.5)+
    labs(x = '', y = 'Reclutamientos ',colour='Asesorías')  +
    scale_x_continuous(breaks = seq(from = 1990, to = 2021, by = 5)) +
    scale_colour_manual("",values=c("orange","green","blue","red","black"))+
    scale_fill_manual("",values=c("grey30"))+
    theme_bw(base_size=8) +
     ggtitle('')+
     theme(plot.title = element_text(hjust = 0.5),legend.position="none")

BD <- ggplot(SSBtcomp) + 
     geom_ribbon(data=VarPob,aes(ymin=lowerBD2, ymax=upperBD2, x=x, fill = "IC"), alpha = 0.2)+
     geom_line(aes(y=SSBt_sept19, x=x, colour = year_retros[nretros]), size=0.5)+
    geom_line(aes(y=SSBt_mar20, x=x, colour = year_retros[nretros-1]), size=0.5)+
    geom_line(aes(y=SSBt_jul20, x=x, colour = year_retros[nretros-2]), size=0.5)+
    geom_line(aes(y=SSBt_sept20, x=x, colour = year_retros[nretros-3]), size=0.5)+
    geom_line(aes(y=SSBt_mar21, x=x, colour = year_retros[nretros-4]), size=0.5)+
    labs(x = '', y = 'Biomasa desovante (t)',colour='Asesorías')  +
    scale_x_continuous(breaks = seq(from = 1990, to = 2021, by = 5)) +
    scale_colour_manual("",values=c("orange","green","blue","red","black"))+
    scale_fill_manual("",values=c("grey30"))+
    theme_bw(base_size=8) +
     ggtitle('')+
     theme(plot.title = element_text(hjust = 0.5))

Ft <- ggplot(Ftcomp) + 
    geom_ribbon(data=VarPob,aes(ymin=lowerFt2, ymax=upperFt2, x=x, fill = "IC"), alpha = 0.2)+
    geom_line(aes(y=Ft_sept19, x=x, colour = year_retros[nretros]), size=0.5)+
    geom_line(aes(y=Ft_mar20, x=x, colour = year_retros[nretros-1]), size=0.5)+
    geom_line(aes(y=Ft_jul20, x=x, colour = year_retros[nretros-2]), size=0.5)+
    geom_line(aes(y=Ft_sept20, x=x, colour = year_retros[nretros-3]), size=0.5)+
    geom_line(aes(y=Ft_mar21, x=x, colour = year_retros[nretros-4]), size=0.5)+
    labs(x = '', y = 'Mortalidad por pesca (F)',colour='Asesorías')  +
    scale_x_continuous(breaks = seq(from = 1990, to = 2021, by = 5)) +
    scale_colour_manual("",values=c("orange","green","blue","red","black"))+
    scale_fill_manual("",values=c("grey30"))+
    theme_bw(base_size=8) +
    ggtitle('')+
    theme(plot.title = element_text(hjust = 0.5),legend.position="none")

Rt/BD/Ft 
```


```{r Dat_RetrospectivoMarzo, echo=T, message=FALSE, warning=FALSE, include=T}
dir<-paste(dir.0,"/Retrospectivo_marz",sep="")
setwd(dir)
admb<-"MAE0321"

years<-rep2$years
nyears<-length(years)
retros<-seq(1,5)
nretros<-length(retros)
year_retros<-as.factor(years[(nyears-(nretros-1)):nyears])
                      
retroR      <- matrix(0,nrow=nyears,ncol=nretros+1)
retroBD     <- matrix(0,nrow=nyears,ncol=nretros+1)
retroF      <- matrix(0,nrow=nyears,ncol=nretros+1)

for(i in 1:length(retros)){
  rep<- reptoRlist(paste(admb,"s",i,".rep",sep=""))
  retroR[,i+1] <- c(rep$Reclutas,rep(NA,i-1))
  retroBD[,i+1] <- c(rep$SSB,rep(NA,i-1))
  retroF[,i+1]  <- c(rep$Ftot,rep(NA,i-1)) }


# retrospectivo relativo (cálculo)
    mohn.r       <- rep(NA, nretros)
    rel.diff.r   <- matrix(NA, nrow=nyears, ncol=(nretros))
    mohn.ssb     <- rep(NA, nretros)
    rel.diff.ssb <- matrix(NA, nrow=nyears, ncol=(nretros))
    mohn.f       <- rep(NA, nretros)
    rel.diff.f   <- matrix(NA, nrow=nyears, ncol=(nretros))

    for(j in 1:nretros){
      rel.diff.r[,j] <- (retroR[,(j+1)]-retroR[,2])/retroR[,2]
      mohn.r[j]      <- rel.diff.r[(nyears-j),j]
      rel.diff.ssb[,j] <- (retroBD[,(j+1)]-retroBD[,2])/retroBD[,2]
      mohn.ssb[j]      <- rel.diff.ssb[(nyears-j),j]
      rel.diff.f[,j]   <- (retroF[,(j+1)]-retroF[,2])/retroF[,2]
      mohn.f[j]        <- rel.diff.f[(nyears-j),j]}
    
    ave.mohn.r    <- mean(mohn.r)
    ave.mohn.ssb  <- mean(mohn.ssb)
    ave.mohn.f    <- mean(mohn.f)
    
 # Arreglo datos

#Para retrospectivo tradicional
Rt_retro<- data.frame(x=years, y1=retroR[,2],y2=retroR[,3],y3=retroR[,4],y4=retroR[,5],y5=retroR[,6],
                      lower = (Rt2 -1.96*Rt2std), upper = (Rt2+1.96*Rt2std))
BD_retro<- data.frame(x=years, y1=retroBD[,2],y2=retroBD[,3],y3=retroBD[,4],y4=retroBD[,5],y5=retroBD[,6],
                      lower = (BD2 -1.96*BD2std), upper = (BD2+1.96*BD2std))
Ft_retro<- data.frame(x=years, y1=retroF[,2],y2=retroF[,3],y3=retroF[,4],y4=retroF[,5],y5=retroF[,6], 
                      lower = exp(Ft2-1.96*Ft2std), upper = exp(Ft2+1.96*Ft2std))

#Para restrospectivo relativo
Rt_retroRel<- data.frame(x=years, y1=rel.diff.r[,1],y2=rel.diff.r[,2],y3=rel.diff.r[,3],y4=rel.diff.r[,4],y5=rel.diff.r[,5])
BD_retroRel<- data.frame(x=years, y1=rel.diff.ssb[,1],y2=rel.diff.ssb[,2],y3=rel.diff.ssb[,3],y4=rel.diff.ssb[,4],y5=rel.diff.ssb[,5])
Ft_retroRel<- data.frame(x=years, y1=rel.diff.f[,1],y2=rel.diff.f[,2],y3=rel.diff.f[,3],y4=rel.diff.f[,4],y5=rel.diff.f[,5])

```

```{r Fig33, echo=T, message=FALSE, warning=FALSE, include=T, fig.align="center", fig.height=10, fig.width=10,fig.path=dir.Fig,dev=fig}

#Retrospectivo tradicional
Rt <- ggplot(Rt_retro) + 
    geom_ribbon(aes(ymin=lower, ymax=upper, x=x, fill = "IC asintótico"), alpha = 0.2)+
    geom_line(aes(y=y1, x=x, colour = year_retros[nretros]), size=0.5)+
    geom_line(aes(y=y2, x=x, colour = year_retros[nretros-1]), size=0.5)+
    geom_line(aes(y=y3, x=x, colour = year_retros[nretros-2]), size=0.5)+
    geom_line(aes(y=y4, x=x, colour = year_retros[nretros-3]), size=0.5)+
    geom_line(aes(y=y5, x=x, colour = year_retros[nretros-4]), size=0.5)+
    labs(x = '', y = 'Reclutamientos ',colour='Asesorías')  +
    scale_x_continuous(breaks = seq(from = 1995, to = 2020, by = 10)) +
    scale_colour_manual("",values=c("orange","green","blue","red","black"))+
    scale_fill_manual("",values=c("grey30"))+
    theme_bw(base_size=8) +
     ggtitle('')+
     theme(plot.title = element_text(hjust = 0.5),legend.position="top")

BD <- ggplot(BD_retro) + 
     geom_ribbon(aes(ymin=lower, ymax=upper, x=x, fill = ""), alpha = 0.2)+
     geom_line(aes(y=y1, x=x, colour = year_retros[nretros]), size=0.5)+
    geom_line(aes(y=y2, x=x, colour = year_retros[nretros-1]), size=0.5)+
    geom_line(aes(y=y3, x=x, colour = year_retros[nretros-2]), size=0.5)+
    geom_line(aes(y=y4, x=x, colour = year_retros[nretros-3]), size=0.5)+
    geom_line(aes(y=y5, x=x, colour = year_retros[nretros-4]), size=0.5)+
    labs(x = '', y = 'Biomasa desovante (t)',colour='Asesorías')  +
    scale_x_continuous(breaks = seq(from = 1995, to = 2020, by = 10)) +
    scale_colour_manual("",values=c("orange","green","blue","red","black"))+
    scale_fill_manual("",values=c("grey30"))+
    theme_bw(base_size=8) +
     ggtitle('')+
     theme(plot.title = element_text(hjust = 0.5),legend.position="none")

Ft <- ggplot(Ft_retro) + 
    geom_ribbon(aes(ymin=lower, ymax=upper, x=x, fill = ""), alpha = 0.2)+
    geom_line(aes(y=y1, x=x, colour = year_retros[nretros]), size=0.5)+
    geom_line(aes(y=y2, x=x, colour = year_retros[nretros-1]), size=0.5)+
    geom_line(aes(y=y3, x=x, colour = year_retros[nretros-2]), size=0.5)+
    geom_line(aes(y=y4, x=x, colour = year_retros[nretros-3]), size=0.5)+
    geom_line(aes(y=y5, x=x, colour = year_retros[nretros-4]), size=0.5)+
    labs(x = '', y = 'Mortalidad por pesca (F)',colour='Asesorías')  +
    scale_x_continuous(breaks = seq(from = 1995, to = 2020, by = 10)) +
    scale_colour_manual("",values=c("orange","green","blue","red","black"))+
    scale_fill_manual("",values=c("grey30"))+
    theme_bw(base_size=8) +
    ggtitle('')+
    theme(plot.title = element_text(hjust = 0.5),legend.position="none")

#Retrospectivo relativo
Rtrel <- ggplot(Rt_retroRel) + lims(y=c(-1,1)) +
    geom_line(aes(y=y1, x=x, colour = year_retros[nretros]), size=0.5)+
    geom_line(aes(y=y2, x=x, colour = year_retros[nretros-1]), size=0.5)+
    geom_line(aes(y=y3, x=x, colour = year_retros[nretros-2]), size=0.5)+
    geom_line(aes(y=y4, x=x, colour = year_retros[nretros-3]), size=0.5)+
    geom_line(aes(y=y5, x=x, colour = year_retros[nretros-4]), size=0.5)+
   annotate("text", x=2000, y=0.5,label=paste("Rho =",round(ave.mohn.r,2))) +
    labs(x = '', y = 'Diferencia porcentual del último año',colour='Asesorías')  +
    scale_x_continuous(breaks = seq(from = 1995, to = 2020, by = 10)) +
    scale_colour_manual("",values=c("orange","green","blue","red","black"))+
    scale_fill_manual("",values=c("grey30"))+
    theme_bw(base_size=8) +
     ggtitle('')+
     theme(plot.title = element_text(hjust = 0.5),legend.position="none")

BDrel <- ggplot(BD_retroRel) + lims(y=c(-1,1)) +
     geom_line(aes(y=y1, x=x, colour = year_retros[nretros]), size=0.5)+
    geom_line(aes(y=y2, x=x, colour = year_retros[nretros-1]), size=0.5)+
    geom_line(aes(y=y3, x=x, colour = year_retros[nretros-2]), size=0.5)+
    geom_line(aes(y=y4, x=x, colour = year_retros[nretros-3]), size=0.5)+
    geom_line(aes(y=y5, x=x, colour = year_retros[nretros-4]), size=0.5)+
   annotate("text", x=2000, y=0.5,label=paste("Rho =",round(ave.mohn.ssb,2))) +
    labs(x = '', y = 'Diferencia porcentual del último año',colour='Asesorías')  +
    scale_x_continuous(breaks = seq(from = 1995, to = 2020, by = 10)) +
    scale_colour_manual("",values=c("orange","green","blue","red","black"))+
    scale_fill_manual("",values=c("grey30"))+
    theme_bw(base_size=8) +
     ggtitle('')+
     theme(plot.title = element_text(hjust = 0.5),legend.position="none")

Ftrel <- ggplot(Ft_retroRel) + lims(y=c(-1,1)) +
    geom_line(aes(y=y1, x=x, colour = year_retros[nretros]), size=0.5)+
    geom_line(aes(y=y2, x=x, colour = year_retros[nretros-1]), size=0.5)+
    geom_line(aes(y=y3, x=x, colour = year_retros[nretros-2]), size=0.5)+
    geom_line(aes(y=y4, x=x, colour = year_retros[nretros-3]), size=0.5)+
    geom_line(aes(y=y5, x=x, colour = year_retros[nretros-4]), size=0.5)+
   annotate("text", x=2000, y=0.5,label=paste("Rho =",round(ave.mohn.f,2))) +
    labs(x = '', y = 'Diferencia porcentual del último año',colour='Asesorías')  +
    scale_x_continuous(breaks = seq(from = 1995, to = 2020, by = 10)) +
    scale_colour_manual("",values=c("orange","green","blue","red","black"))+
    scale_fill_manual("",values=c("grey30"))+
    theme_bw(base_size=8) +
    ggtitle('')+
    theme(plot.title = element_text(hjust = 0.5),legend.position="none")

Rt/BD/Ft |Rtrel/BDrel/Ftrel

```


```{r Fig34,eval=T, warning=F, include=T, message=F, echo=T,fig.height=4,fig.width=5,fig.align="center",fig.path=dir.Fig,dev=fig}

dir<-paste(dir.0,"/Verosimilitud_marz",sep="")
setwd(dir)

casos <-23
logRo    <- rep(0,casos)
likeval  <- matrix(ncol=15,nrow=casos)
slikeval <- matrix(ncol=16,nrow=casos)

for(i in 1:casos){
report      <- reptoRlist(paste(dir,"/MAE0321s",i,".rep",sep=""))
logRo[i]    <- report$log_Ro
likeval[i,] <- report$likeval}

like    <- data.frame(round(likeval,3),Total=apply(likeval,1,sum))
minLik  <- apply(like,2,min)                         # busca el mínimo
for(i in 1:16){slikeval[,i]<-like[,i]-minLik[i]}    # Estandarización

names<-c("Ro","Reclas","Pelaces","Desembarques","MPDH","propF",
	"propRecl","propPel","prepPelTall","DesvRt","qreclas","qpela","PenFt",
	"PenFspr","NA","NA","Total")
# Tabla verosimilitud
TLk1 <- data.frame(exp(logRo),like);colnames(TLk1)<-names
# Tabla estandarizada
TLk2 <- data.frame(exp(logRo),slikeval);colnames(TLk2)<-names

par(mar=c(4,4,1,1))
plot(TLk2$Ro,TLk2$Total,type="l",lwd=3,ylim=c(0,3),xlim=c(10^4,32*10^4),
	xaxs= "i",	ylab="L-min(L)",xlab="Ro",las=1,main='Asesoría de marzo 2021',cex.main=0.8,cex.axis=0.8,cex.lab=0.8)
lines(c(0,TLk2$Ro),rep(2,casos+1),lty=2,lwd=2)
for(i in 2:8){lines(TLk2$Ro,TLk2[,i],col=i,lty=2,lwd=2)}
#for(i in 9:14){lines(TLk2$Ro,TLk2[,i],col=i,lty=3,lwd=2)}
legend(210000,2.9,names[c(17,2:8)],col=1:8,lty=c(1,rep(2,7)),lwd=2,bty="n",cex=0.75)
#legend(230000,1.5,names[9:14],col=9:14,lty=3,lwd=2,bty="n",cex=0.8)

```


```{r Variables_sept, echo=T,message=FALSE, warning=FALSE, include=T}

years1<-rep2$years
nyears1<-length(years1)

Rt1      <- c(subset(std1,name=="Reclutas")$value,NA) 
Rt1std   <- c(subset(std1,name=="Reclutas")$std,NA)
BT1      <- c(subset(std1,name=="BT")$value,NA)   
BT1std   <- c(subset(std1,name=="BT")$std,NA)
BD1      <- c(subset(std1,name=="SSB")$value,NA)   
BD1std   <- c(subset(std1,name=="SSB")$std,NA)
Ft1      <- c(subset(std1,name=="log_Ft")$value,NA)   
Ft1std   <- c(subset(std1,name=="log_Ft")$std,NA)

VarPobSep<- data.frame(x=years1, Rt1=Rt1,BT1=BT1,BD1=BD1,Ft1=exp(Ft1), 
         lowerRt1 = (Rt1 -1.96*Rt1std), upperRt1 = (Rt1+1.96*Rt1std),
         lowerBT1 = (BT1 -1.96*BT1std), upperBT1 = (BT1+1.96*BT1std),
         lowerBD1 = (BD1 -1.96*BD1std), upperBD1 = (BD1+1.96*BD1std),
         lowerFt1 = exp(Ft1 -1.96*Ft1std), upperFt1 = exp(Ft1+1.96*Ft1std))
```

```{r Variables_marzo, echo=T,message=FALSE, warning=FALSE, include=T}

years2<-rep2$years
nyears2<-length(years2)

Rt2      <- subset(std2,name=="Reclutas")$value 
Rt2std   <- subset(std2,name=="Reclutas")$std
BT2      <- subset(std2,name=="BT")$value   
BT2std   <- subset(std2,name=="BT")$std
BD2      <- subset(std2,name=="SSB")$value   
BD2std   <- subset(std2,name=="SSB")$std
Ft2      <- subset(std2,name=="log_Ft")$value   
Ft2std   <- subset(std2,name=="log_Ft")$std

VarPobMar<- data.frame(x=years2, Rt2=Rt2,BT2=BT2,BD2=BD2,Ft2=exp(Ft2), 
         lowerRt2 = (Rt2 -1.96*Rt2std), upperRt2 = (Rt2+1.96*Rt2std),
         lowerBT2 = (BT2 -1.96*BT2std), upperBT2 = (BT2+1.96*BT2std),
         lowerBD2 = (BD2 -1.96*BD2std), upperBD2 = (BD2+1.96*BD2std),
         lowerFt2 = exp(Ft2 -1.96*Ft2std), upperFt2 = exp(Ft2+1.96*Ft2std))
```

```{r Fig35, echo=FALSE, message=FALSE, warning=FALSE, include=T, fig.align="center", fig.height=6, fig.width=8,fig.path=dir.Fig,dev=fig}


Rt <- ggplot() + 
    geom_line(data=VarPobMar,aes(y=Rt2, x=x, colour = "marzo 2021"), size=0.5)+
    geom_line(data=VarPobSep,aes(y=Rt1, x=x, colour = "septiembre 2020"), size=0.5)+
    geom_ribbon(data=VarPobMar,aes(ymin=lowerRt2, ymax=upperRt2, x=x, fill = "IC"), alpha = 0.2)+
    geom_ribbon(data=VarPobSep,aes(ymin=lowerRt1, ymax=upperRt1, x=x, fill = ""), alpha = 0.2)+
    geom_hline(yintercept = mean(VarPobMar$Rt2),colour='black',lty=2) +
     annotate("text", x=2000, y=mean(VarPobMar$Rt2),label=expression("R"[promedio])) +
    labs(x = '', y = 'Reclutamientos',colour='Asesorías')  +
     scale_x_continuous(breaks = seq(from = 1960, to = 2021, by = 2)) +
    scale_colour_manual("",values=c('red',"black"))+
    scale_fill_manual("",values=c("grey30",'gray75'))+
    theme_bw(base_size=8) +
     ggtitle('')+
     theme(plot.title = element_text(hjust = 0.5),legend.position="top")

BT <- ggplot() + 
     geom_line(data=VarPobMar,aes(y=BT2, x=x, colour = "marzo 2021"), size=0.5)+
     geom_line(data=VarPobSep,aes(y=BT1, x=x, colour = "septiembre 2020"), size=0.5)+
     geom_ribbon(data=VarPobMar,aes(ymin=lowerBT2, ymax=upperBT2, x=x, fill = "IC"), alpha = 0.2)+
     geom_ribbon(data=VarPobSep,aes(ymin=lowerBT1, ymax=upperBT1, x=x, fill = ""), alpha = 0.2)+
   geom_hline(data=VarPobMar,yintercept = mean(BT2),colour='black',lty=2) +
     annotate("text", x=2000, y=mean(BT2),label=expression("BT"[promedio])) +
    labs(x = '', y = 'Biomasa total (t)',colour='Asesorías')  +
     scale_x_continuous(breaks = seq(from = 1960, to = 2021, by = 2)) +
    scale_colour_manual("",values=c('red',"black"))+
    scale_fill_manual("",values=c("grey30",'gray75'))+
    theme_bw(base_size=8) +
     ggtitle('')+
     theme(plot.title = element_text(hjust = 0.5),legend.position="none")

BD <- ggplot() + 
     geom_line(data=VarPobMar,aes(y=BD2, x=x, colour = "marzo 2021"), size=0.5)+
     geom_line(data=VarPobSep,aes(y=BD1, x=x, colour = "septiembre 2020"), size=0.5)+
     geom_ribbon(data=VarPobMar,aes(ymin=lowerBD2, ymax=upperBD2, x=x, fill = "IC"), alpha = 0.2)+
     geom_ribbon(data=VarPobSep,aes(ymin=lowerBD1, ymax=upperBD1, x=x, fill = ""), alpha = 0.2)+
     geom_hline(data=VarPobMar,yintercept = mean(BD2),colour='black',lty=2) +
     annotate("text", x=2000, y=mean(BD2),label=expression("BD"[promedio])) +
     labs(x = '', y = 'Biomasa desovante (t)',colour='Asesorías')  +
     scale_x_continuous(breaks = seq(from = 1960, to = 2021, by = 2)) +
     scale_colour_manual("",values=c('red',"black"))+
     scale_fill_manual("",values=c("grey30",'gray75'))+
     theme_bw(base_size=8) +
     ggtitle('')+
     theme(plot.title = element_text(hjust = 0.5),legend.position="top")

Ft <- ggplot() + 
    geom_line(data=VarPobMar,aes(y=Ft2, x=x, colour = "marzo 2021"), size=0.5)+
    geom_line(data=VarPobSep,aes(y=Ft1, x=x, colour = "septiembre 2020"), size=0.5)+
    geom_ribbon(data=VarPobMar,aes(ymin=lowerFt2, ymax=upperFt2, x=x, fill = "IC"), alpha = 0.2)+
    geom_ribbon(data=VarPobSep,aes(ymin=lowerFt1, ymax=upperFt1, x=x, fill = ""), alpha = 0.2)+
     geom_hline(yintercept = median(VarPobMar$Ft2),colour='black',lty=2) +
     annotate("text", x=2018, y=median(VarPobMar$Ft2),label=expression("F"[mediana])) +
    labs(x = '', y = 'Mortalidad por pesca (F)',colour='Asesorías')  +
    scale_x_continuous(breaks = seq(from = 1960, to = 2021, by = 2)) +
    scale_colour_manual("",values=c('red',"black"))+
    scale_fill_manual("",values=c("grey30",'gray75'))+
    theme_bw(base_size=8) +
     ggtitle('')+
     theme(plot.title = element_text(hjust = 0.5),legend.position="none")

Rt/BT | (BD/Ft)

```


```{r Tabla_20, echo=T,warning=FALSE,include=T}
yearsb<-c("1990/91","1991/92","1992/93","1993/94","1994/95","1995/96","1996/97","1997/98","1998/99","1999/00","2000/01","2001/02","2002/03","2003/04","2004/05","2005/06","2006/07","2007/08","2008/09","2009/10","2010/11","2011/12","2012/13","2013/14","2014/15","2015/16","2016/17","2017/18","2018/19","2019/20",'2020/21')

Rt1      <- c(subset(std1,name=="Reclutas")$value,NA) 
Rt1std   <- c(subset(std1,name=="Reclutas")$std,NA)
BT1      <- c(subset(std1,name=="BT")$value,NA)   
BT1std   <- c(subset(std1,name=="BT")$std,NA)
BD1      <- c(subset(std1,name=="SSB")$value,NA)   
BD1std   <- c(subset(std1,name=="SSB")$std,NA)
Ft1      <- c(subset(std1,name=="log_Ft")$value,NA)   
Ft1std   <- c(subset(std1,name=="log_Ft")$std,NA)


Rt2      <- subset(std2,name=="Reclutas")$value 
Rt2std   <- subset(std2,name=="Reclutas")$std
BT2      <- subset(std2,name=="BT")$value   
BT2std   <- subset(std2,name=="BT")$std
BD2      <- subset(std2,name=="SSB")$value   
BD2std   <- subset(std2,name=="SSB")$std
Ft2      <- subset(std2,name=="log_Ft")$value   
Ft2std   <- subset(std2,name=="log_Ft")$std

VarPobl1<- cbind('Año'=yearsb,
                 "$BD_{sept}$"=c(BD1),
                 "$BD_{marzo}$"=c(BD2),
                 "$BT_{sept}$"=c(BT1),
                 "$BT_{marzo}$"=c(BT2),
                 "$R_{sept}$"=c(Rt1),
                 "$R_{marzo}$"=c(Rt2),
                 "$F_{sept}$"=c(round(exp(Ft1),3)),
                 "$F_{marzo}$"=c(round(exp(Ft2),3)))
kable(VarPobl1)

#setwd(dir.basedatos)
write.csv(VarPobl1, file="Tabla_20_indicadorespoblacionales.csv")
#setwd(dir.1)
```

```{r Tabla_20_promedios, echo=T,warning=FALSE,include=T,eval=F}

# Reclutimientos asesoría marzo 2021
Rprom_1991_2007<-mean(Rt2[1:17])
Rprom_2008_2012<-mean(Rt2[18:22])
Rprom_2013_2021<-mean(Rt2[23:31])
Rprom_2013_2020<-mean(Rt2[23:30])
Rprom_historico<-mean(Rt2)

Rprom<-rbind(Rprom_1991_2007,
      Rprom_2008_2012,
      Rprom_2013_2021,
      Rprom_2013_2020,
      Rprom_historico)

#diferencia del Rúltimo año y los promedios de los tres períodos principales
Rlast_1991_2007<-1-(Rt2[31]/Rprom_1991_2007)
Rlast_2008_2012<-1-(Rt2[31]/Rprom_2008_2012)
Rlast_2013_2021<-1-(Rt2[31]/Rprom_2013_2021)
Rlast_2013_2020<-1-(Rt2[31]/Rprom_2013_2020)
Rlast_historico<-1-(Rt2[31]/Rprom_historico)

difR<-rbind(Rlast_1991_2007,
      Rlast_2008_2012,
      Rlast_2013_2021,
      Rlast_2013_2020,
      Rlast_historico)

# Biomasa total (BT) asesoría marzo 2021
BTprom_1991_2007<-mean(BT2[1:17])
BTprom_2008_2012<-mean(BT2[18:22])
BTprom_2013_2021<-mean(BT2[23:31])
BTprom_2013_2020<-mean(BT2[23:30])
BTprom_historico<-mean(BT2)

BTprom<-rbind(BTprom_1991_2007,
      BTprom_2008_2012,
      BTprom_2013_2021,
      BTprom_2013_2020,
      BTprom_historico)

#diferencia del BT último año y los promedios de los tres períodos principales
BTlast_1991_2007<-1-(BT2[31]/BTprom_1991_2007)
BTlast_2008_2012<-1-(BT2[31]/BTprom_2008_2012)
BTlast_2013_2021<-1-(BT2[31]/BTprom_2013_2021)
BTlast_2013_2020<-1-(BT2[31]/BTprom_2013_2020)
BTlast_historico<-1-(BT2[31]/BTprom_historico)

difBT<- rbind(BTlast_1991_2007,
      BTlast_2008_2012,
      BTlast_2013_2021,
      BTlast_2013_2020,
      BTlast_historico)


# Biomasa desovante (BD) asesoría marzo 2021

BDprom_1991_2007<-mean(BD2[1:17])
BDprom_2008_2012<-mean(BD2[18:22])
BDprom_2013_2021<-mean(BD2[23:31])
BDprom_2013_2020<-mean(BD2[23:30])
BDprom_historico<-mean(BD2)
  
BDprom<-rbind(BDprom_1991_2007,
      BDprom_2008_2012,
      BDprom_2013_2021,
      BDprom_2013_2020,
      BDprom_historico)

#diferencia del BD último año y los promedios de los tres períodos principales
BDlast_1991_2007<-1-(BD2[31]/BDprom_1991_2007)
BDlast_2008_2012<-1-(BD2[31]/BDprom_2008_2012)
BDlast_2013_2021<-1-(BD2[31]/BDprom_2013_2021)
BDlast_2013_2020<-1-(BD2[31]/BDprom_2013_2020)
BDlast_historico<-1-(BD2[31]/BDprom_historico)

difBD<-rbind(BDlast_1991_2007,
      BDlast_2008_2012,
      BDlast_2013_2021,
      BDlast_2013_2020,
      BDlast_historico)


diferencias<-cbind(difR,difBT,difBD,Rprom,BTprom,BDprom)
colnames(diferencias)<-c("difRt","difBT","difBD","Rprom","BTprom","BDprom")
diferencias

write.csv(diferencias, file="Tabla_20_diferencias.csv")


```


```{r Fig36,warning=F, include=T, message=F, echo=T,fig.height=3.5,fig.width=3.5,fig.align="center",fig.path=dir.Fig,dev=fig}

sel_Flota<-rep2$Sel_flota[1,]
sel_CruV <-rep2$Sel_reclas[1,]
sel_CruO <-rep2$Sel_pelaces[1,]

g1 <- ggplot () +
     #lineas
     geom_line(aes(x=age,y=sel_Flota))+
     geom_line(aes(x=age,y=sel_CruV))+
     geom_line(aes(x=age,y=sel_CruO),linetype="dashed")+
     #puntos
     geom_point(aes(x=age,y=sel_Flota,shape="FLota"),size=2.5) +
     geom_point(aes(x=age,y=sel_CruV,shape="Cruceros de Verano"),size=2.5) +
     geom_point(aes(x=age,y=sel_CruO,shape="Cruceros de Otoño"),size=2.5) +
     #parámetros
     labs(x = 'Edad (años)', y = 'Patrón de explotación',shape="Selectividades") +
     ggtitle("")+
     theme_bw(base_size=11) + 
     theme(plot.title = element_text(hjust = 0.5),legend.justification=c(1.1,0), legend.position=c(1,0.1))
g1

```


```{r Data_PBR_biologico_sept, echo=T}
#PBR año biologico
Amax        <- dat1$nedades 
Fmort 	    <- seq(0,3.5,0.02)           
nf          <- length(Fmort) 
R0 		      <- 1  
#datos de entrada 
Dat<-list()
Dat$M		    <- dat1$par[5]             
Dat$Tspw	  <- dat1$Dt[3]              
Dat$Mad	    <- dat1$madurezsexual        
Dat$Wmed	  <- colMeans(dat1$Wmed)      
Dat$Wini	  <- colMeans(dat1$Wini) 
Dat$Sel     <- rep1$Sel_flota[1,] 

Rmed1        <- mean(Rt1,na.rm = T)           
Bmed1        <- mean(BD1,na.rm = T)         
Fmedian1     <- exp(median(Ft1,na.rm = T))

Bobj        <-c(.85,.80,.60,.55,.52,.50,.45,.40,.30,.325,0.425)
Fobj      	<- optim(par=rep(0.,11),fn=SPRFpbr,method='BFGS')

SPR1 		    <- SPRFmort(Rmed1,c(0,Fobj$par,Fmedian1,rep1$Ftot[25]),Amax,Dat) 
pSPR_Fmh1    <- as.numeric(SPR1[13,4])                     # Paso 2: Cálculo de la curva SPR
pB_Fmh1      <- pSPR_Fmh1-0.05                             # Paso 3: Aproximación obtención de %BD(Fmh)
SPRcurv1 		<- SPRFmort(R0,Fmort,Amax,Dat) 
```

```{r Data_PBR_biologico_marzo, echo=T}
#PBR año biologico
Amax        <- dat2$nedades 
Fmort 	    <- seq(0,3.5,0.02)           
nf          <- length(Fmort) 
R0 		      <- 1  
#datos de entrada 
Dat<-list()
Dat$M		    <- dat2$par[5]             
Dat$Tspw	  <- dat2$Dt[3]              
Dat$Mad	    <- dat2$madurezsexual        
Dat$Wmed	  <- colMeans(dat2$Wmed)      
Dat$Wini	  <- colMeans(dat2$Wini) 
Dat$Sel     <- rep2$Sel_flota[1,] 

Rmed2        <- mean(Rt2)           
Bmed2        <- mean(BD2)         
Fmedian2     <- exp(median(Ft2))

Bobj        <-c(.85,.80,.60,.55,.52,.50,.45,.40,.30,.325,0.425)
Fobj      	<- optim(par=rep(0.,11),fn=SPRFpbr,method='BFGS')

SPR2 		    <- SPRFmort(Rmed2,c(0,Fobj$par,Fmedian2,rep2$Ftot[25]),Amax,Dat) 
pSPR_Fmh2    <- as.numeric(SPR2[13,4])                     # Paso 2: Cálculo de la curva SPR
pB_Fmh2      <- pSPR_Fmh2-0.05                             # Paso 3: Aproximación obtención de %BD(Fmh)
SPRcurv2 		<- SPRFmort(R0,Fmort,Amax,Dat) 
```

```{r pbrs septiembre, echo=T}
# ASESORÍA DE SEPTIEMBRE
Bo1           <- rep1$SSBpbr[1]                         # Paso 4: Obtenci?n de Bo
BRMS1         <- rep1$SSBpbr[3]                         # Paso 5: Obtenci?n de Brms = 60%SPRo = 55%Bo
FRMS1         <- rep1$Fs[2]
BLIM1         <- Bo1*0.275                              # Paso 6: Obtenci?n de Blim = 20%Bo 
FLIM1         <- rep1$Fs[3]                             # Paso 6: Obtenci?n de Flim = 30%SPRo
SpB1          <- BD1                                  # BD serie hist?rica de evaluaci?n de stock 
SpBSE1        <- BD1std                               # desviaci?n estandar BD
ln_Fyr1       <- Ft1                                    # logaritmo de Ft
ln_FSE1       <- Ft1std                                 # logaritmo de la desviaci?n standar de Ft
```

```{r pbrs marzo, echo=T}
# ASESORÍA DE SEPTIEMBRE
Bo2           <- rep2$SSBpbr[1]                         # Paso 4: Obtenci?n de Bo
BRMS2         <- rep2$SSBpbr[3]                         # Paso 5: Obtenci?n de Brms = 60%SPRo = 55%Bo
FRMS2         <- rep2$Fs[2]
BLIM2         <- Bo2*0.275                              # Paso 6: Obtenci?n de Blim = 20%Bo 
FLIM2         <- rep2$Fs[3]                             # Paso 6: Obtenci?n de Flim = 30%SPRo
SpB2          <- BD2                                  # BD serie hist?rica de evaluaci?n de stock 
SpBSE2        <- BD2std                               # desviaci?n estandar BD
ln_Fyr2       <- Ft2                                    # logaritmo de Ft
ln_FSE2       <- Ft2std                                 # logaritmo de la desviaci?n standar de Ft
```


```{r Tabla_17 PBRs, echo=T,eval=F}
Tabla3.1<-rbind( "BDpromedio"=c(round(Bmed1/10^3,0),
                                round(Bmed2/10^3,0)),
                 "Fmh"=c(round(Fmedian1,2),
                         round(Fmedian2,2)), 
                 "%BDPR_Fmh"=c(pSPR_Fmh1*100,
                               pSPR_Fmh2*100), 
                 "%BDPR_F~RMS~"=c(60,
                                  60),
                 "%BD_Fmh"=c(pB_Fmh1*100,
                             pB_Fmh2*100),
                 "%BD_F~RMS~"=c(55,
                                55),
                 "BDo"=c(round(Bo1/10^3,0),
                         round(Bo2/10^3,0)),
                 "BD55%"=c(round(BRMS1/10^3,0),
                           round(BRMS2/10^3,0)),
                 "BD27.5%"=c(round(BLIM1/10^3,0),
                             round(BLIM2/10^3,0)))

colnames(Tabla3.1)<-c("Septiembre","Marzo")
kable(Tabla3.1, align = 'c')

write.csv(Tabla3.1, file="Tabla21_PBRsporasesoria.csv")


```



```{r Fig37,warning=F, include=T, message=F, echo=T,fig.height=4.5,fig.width=9,fig.align="center",fig.path=dir.Fig,dev=fig}

BD <- ggplot() + 
     geom_line(data=VarPobMar,aes(y=BD2, x=x, colour = "marzo 2021"), size=0.5)+
     geom_line(data=VarPobSep,aes(y=BD1, x=x, colour = "septiembre 2020"), size=0.5)+
     geom_ribbon(data=VarPobMar,aes(ymin=lowerBD2, ymax=upperBD2, x=x, fill = "IC"), alpha = 0.2)+
     geom_ribbon(data=VarPobSep,aes(ymin=lowerBD1, ymax=upperBD1, x=x, fill = ""), alpha = 0.2)+
     geom_hline(yintercept = c(BRMS2,BLIM2,Bo2,Bmed2),colour=c('green3','red','blue','black'))+
     annotate("text", x=c(rep(2012,3),2000), y=c(BRMS2,BLIM2,Bo2,Bmed2),
              label=c(expression("BD"[RMS]),expression("BD"[LIM]),expression("BD"[0]),expression("BD"[promedio]))) +
     labs(x = '', y = 'Biomasa desovante (t)',colour='Asesorías')  +
     scale_x_continuous(breaks = seq(from = 1960, to = 2022, by = 4)) +
     scale_colour_manual("",values=c('red',"black"))+
     scale_fill_manual("",values=c("grey30",'gray75'))+
     theme_bw(base_size=10) +
     ggtitle('')+
     theme(plot.title = element_text(hjust = 0.5),legend.position="top")

Ft <- ggplot() + 
    geom_line(data=VarPobMar,aes(y=Ft2, x=x, colour = "marzo 2021"), size=0.5)+
    geom_line(data=VarPobSep,aes(y=Ft1, x=x, colour = "septiembre 2020"), size=0.5)+
    geom_ribbon(data=VarPobMar,aes(ymin=lowerFt2, ymax=upperFt2, x=x, fill = "IC"), alpha = 0.2)+
    geom_ribbon(data=VarPobSep,aes(ymin=lowerFt1, ymax=upperFt1, x=x, fill = ""), alpha = 0.2)+
     geom_hline(yintercept = c(FRMS2,median(VarPobMar$Ft2)),colour=c('green3','black')) +
     annotate("text", x=c(2011,2001), y=c(FRMS2,median(exp(ln_Fyr2)))+0.05,label=c(expression("F"[RMS]),expression("F"[mh]))) +
    labs(x = '', y = 'Mortalidad por pesca (F)',colour='Asesorías')  +
    scale_x_continuous(breaks = seq(from = 1960, to = 2022, by = 4)) +
    scale_colour_manual("",values=c('red',"black"))+
    scale_fill_manual("",values=c("grey30",'gray75'))+
    theme_bw(base_size=10) +
     ggtitle('')+
     theme(plot.title = element_text(hjust = 0.5),legend.position="none")

BD + Ft

```

```{r Fig38,warning=F, include=T, message=F, echo=T,fig.height=3.5,fig.width=7.5,fig.align="center",fig.path=dir.Fig,dev=fig}

sel_Flota <- rep2$Sel_flota[1,]
madurez   <- dat2$madurezsexual
Fspr      <- SPRcurv2[,1]
BDspr     <- SPRcurv2[,4]

g1 <- ggplot () +
     #lineas
     geom_line(aes(x=age,y=sel_Flota))+
     geom_line(aes(x=age,y=madurez),linetype="dashed")+
     #puntos
     geom_point(aes(x=age,y=sel_Flota,shape="Selectividad de la flota"),size=2.5) +
     geom_point(aes(x=age,y=madurez,shape="Madurez sexual"),size=2.5) +
     #parámetros
     labs(x = 'Edad (años)', y = 'Madurez y selectividad',shape="") +
     ggtitle("")+
     theme_bw(base_size=11) + 
     theme(plot.title = element_text(hjust = 0.5),legend.justification=c(1.1,0), legend.position=c(1,0.1))


g2 <- ggplot () +
     geom_line(aes(x=Fspr,y=BDspr))+
     geom_hline(yintercept = 0.6,colour=c('gray35'),linetype="dashed") +
     geom_vline(xintercept = FRMS2,colour=c('gray35'),linetype="dashed") +
     annotate("text", x=2, y=0.6+0.02,label=c(expression("F"[RMS]))) +
     labs(x = 'Mortalidad por pesca (F)', y = '%BDPR',shape="") +
     ggtitle("")+
     theme_bw(base_size=11) + 
     theme(plot.title = element_text(hjust = 0.5),legend.justification=c(1.1,0), legend.position=c(1,0.1))
g1 + g2
```


```{r Estatus_sept, echo=T,message=FALSE, warning=FALSE, include=T}

years1<-rep2$years
nyears1<-length(years1)
#para serie histórica
Rpr1     <- c(subset(std1,name=="RPRequ3")$value,NA); 
Rpr1std  <- c(subset(std1,name=="RPRequ3")$std,NA)
Frpr1    <- c(subset(std1,name=="Frpr")$value,NA); 
Frpr1std <- c(subset(std1,name=="Frpr")$std,NA)

EstatusSep<- data.frame(x=years1, Rpr1=Rpr1,Frpr1=Frpr1,
         lowerRpr1  = (Rpr1 - 1.96*Rpr1std ), upperRpr1   = (Rpr1 +1.96*Rpr1std ),
         lowerFrpr1 = (Frpr1 -1.96*Frpr1std), upperFrpr1 = (Frpr1 +1.96*Frpr1std))

#Para densidad de probabilidad
rprSEPT     <-subset(std1,name=="RPRequ3")$value[nyears1-1]
rprSEPTstd  <-subset(std1,name=="RPRequ3")$std[nyears1-1]
FrprSEPT    <-subset(std1,name=="Frpr")$value[nyears1-1]
FrprSEPTstd <-subset(std1,name=="Frpr")$std[nyears1-1]

# biomasa desovante vs BDrms
xbs1 <-rnorm(1000, mean = rprSEPT, sd = rprSEPTstd)
xbs  <-seq(min(xbs1),max(xbs1),0.005)
ybs  <-dnorm(xbs, mean = rprSEPT, sd =rprSEPTstd)
icbs <-qnorm(c(0.05,0.95,0.5),rprSEPT,rprSEPTstd)

# mortalidad por pesca vs Frms
xfs1 <- rnorm(1000, mean = FrprSEPT, sd = FrprSEPTstd)
xfs  <-seq(min(xfs1),max(xfs1),0.005)
yfs  <-dnorm(xfs, mean = FrprSEPT, sd =FrprSEPTstd)
icfs <-qnorm(c(0.05,0.95,0.5),FrprSEPT,FrprSEPTstd)

#distribución probabilidad
xxbs      <- c(xbs[xbs>=icbs[1]&xbs<=icbs[2]],rev(xbs[xbs>=icbs[1]&xbs<=icbs[2]]))
yybs      <- c(ybs[xbs>=icbs[1]&xbs<=icbs[2]],rep(0,length(ybs[xbs>=icbs[1]&xbs<=icbs[2]])))
xxfs      <- c(xfs[xfs>=icfs[1]&xfs<=icfs[2]],rev(xfs[xfs>=icfs[1]&xfs<=icfs[2]]))
yyfs      <- c(yfs[xfs>=icfs[1]&xfs<=icfs[2]],rep(0,length(yfs[xfs>=icfs[1]&xfs<=icfs[2]])))

densb_bs  <- data.frame(x=xxbs, y=yybs , t=rep('a', length(xxbs)), r=seq(1,length(xxbs),1))
densb_fs  <- data.frame(x=xxfs, y=yyfs , t=rep('a', length(xxfs)), r=seq(1,length(xxfs),1))

### *Probabilidad de estar bajo BRMS*
#Asesoría Septiembre #P(BD<BDrms) 
pa_sept<-pnorm(1,rprSEPT,rprSEPTstd,lower.tail = TRUE,log.p = F)
### *Probabilidad de estar bajo FRMS*
#Asesoría Septiembre #P(F>Frms)
pb_sept<-1-pnorm(1,FrprSEPT,FrprSEPTstd,lower.tail = TRUE,log.p = F)
### *Probabilidad de estar en zona de sobreexplotacion*
#Asesoría Septiembre #P(BD<BDrms) 
pc_sept<-pnorm(0.9,rprSEPT,rprSEPTstd,lower.tail = TRUE,log.p = F)
### *Probabilidad de estar en zona de colapso*
#Asesoría Septiembre #P(BD<BDrms) 
pd_sept<-pnorm(0.5,rprSEPT,rprSEPTstd,lower.tail = TRUE,log.p = F)
### *Probailidad de sobrepesca*
#Asesoría Septiembre #P(F>Frms)
pe_sept<-1-pnorm(1.1,FrprSEPT,FrprSEPTstd,lower.tail = TRUE,log.p = F)
```


```{r Estatus_marzo, echo=T,message=FALSE, warning=FALSE, include=T}

years2<-rep2$years
nyears2<-length(years2)

#para serie histórica indicadores del estatus
Rpr2     <- subset(std2,name=="RPRequ3")$value; 
Rpr2std  <- subset(std2,name=="RPRequ3")$std
Frpr2    <- subset(std2,name=="Frpr")$value; 
Frpr2std <- subset(std2,name=="Frpr")$std

EstatusMar<- data.frame(x=years2, Rpr2=Rpr2,Frpr2=Frpr2,
         lowerRpr2  = (Rpr2 - 1.96*Rpr2std ), upperRpr2   = (Rpr2 +1.96*Rpr2std ),
         lowerFrpr2 = (Frpr2 -1.96*Frpr2std), upperFrpr2 = (Frpr2+1.96*Frpr2std))

#Para densidad de probabilidad
rprMARZO     <-subset(std2,name=="RPRequ3")$value[nyears2]
rprMARZOstd  <-subset(std2,name=="RPRequ3")$std[nyears2]
FrprMARZO    <-subset(std2,name=="Frpr")$value[nyears2]
FrprMARZOstd <-subset(std2,name=="Frpr")$std[nyears2]
# biomasa desovante vs BDrms - densidad de probabilidad
xbm1 <-rnorm(1000, mean = rprMARZO, sd = rprMARZOstd)
xbm  <-seq(min(xbm1),max(xbm1),0.005)
ybm  <-dnorm(xbm, mean = rprMARZO, sd =rprMARZOstd)
icbm <-qnorm(c(0.05,0.95,0.5),rprMARZO,rprMARZOstd)
# mortalidad por pesca vs Frms - densidad de probabilidad
xfm1 <- rnorm(1000, mean = FrprMARZO, sd = FrprMARZOstd)
xfm  <-seq(min(xfm1),max(xfm1),0.005)
yfm  <-dnorm(xfm, mean = FrprMARZO, sd =FrprMARZOstd)
icfm <-qnorm(c(0.05,0.95,0.5),FrprMARZO,FrprMARZOstd)
#distribución probabilidad
xxbm      <- c(xbm[xbm>=icbm[1]&xbm<=icbm[2]],rev(xbm[xbm>=icbm[1]&xbm<=icbm[2]]))
yybm      <- c(ybm[xbm>=icbm[1]&xbm<=icbm[2]],rep(0,length(ybm[xbm>=icbm[1]&xbm<=icbm[2]])))
xxfm      <- c(xfm[xfm>=icfm[1]&xfm<=icfm[2]],rev(xfm[xfm>=icfm[1]&xfm<=icfm[2]]))
yyfm      <- c(yfm[xfm>=icfm[1]&xfm<=icfm[2]],rep(0,length(yfm[xfm>=icfm[1]&xfm<=icfm[2]])))

densb_bm  <- data.frame(x=xxbm, y=yybm , t=rep('a', length(xxbm)), r=seq(1,length(xxbm),1))
densb_fm  <- data.frame(x=xxfm, y=yyfm , t=rep('a', length(xxfm)), r=seq(1,length(xxfm),1))

### *Probabilidad de estar bajo BRMS*
#Asesoría Septiembre #P(BD<BDrms) 
pa_mar<-pnorm(1,rprMARZO,rprMARZOstd,lower.tail = TRUE,log.p = F)
### *Probabilidad de estar bajo FRMS*
#Asesoría Septiembre #P(F>Frms)
pb_mar<-1-pnorm(1,FrprMARZO,FrprMARZOstd,lower.tail = TRUE,log.p = F)
### *Probabilidad de estar en zona de sobreexplotacion*
#Asesoría Septiembre #P(BD<BDrms) 
pc_mar<-pnorm(0.9,rprMARZO,rprMARZOstd,lower.tail = TRUE,log.p = F)
### *Probabilidad de estar en zona de colapso*
#Asesoría Septiembre #P(BD<BDrms) 
pd_mar<-pnorm(0.5,rprMARZO,rprMARZOstd,lower.tail = TRUE,log.p = F)
### *Probailidad de sobrepesca*
#Asesoría Septiembre #P(F>Frms)
pe_mar<-1-pnorm(1.1,FrprMARZO,FrprMARZOstd,lower.tail = TRUE,log.p = F)

```

```{r Fig39,warning=F, include=T, message=F, echo=T,fig.height=6.5,fig.width=8,fig.align="center",fig.path=dir.Fig,dev=fig}

BD_BDrms <- ggplot() + 
     geom_line(data=EstatusMar,aes(y=Rpr2, x=x, colour = "marzo 2021"), size=0.5)+
     geom_line(data=EstatusSep,aes(y=Rpr1, x=x, colour = "septiembre 2020"), size=0.5)+
     geom_ribbon(data=EstatusMar,aes(ymin=lowerRpr2, ymax=upperRpr2, x=x, fill = "IC"), alpha = 0.2)+
     geom_ribbon(data=EstatusSep,aes(ymin=lowerRpr1, ymax=upperRpr1, x=x, fill = ""), alpha = 0.2)+
     geom_hline(yintercept = c(1,0.5),colour=c('green3','red'))+
     annotate("text", x=c(2012,2012), y=c(1,0.5)+0.06,
              label=c(expression("BD"[RMS]),expression("BD"[LIM]))) +
     labs(x = '', y = expression("BD/BD"[RMS]),colour='Asesorías',tag="a)")  +
     scale_x_continuous(breaks = seq(from = 1960, to = 2062, by = 2)) +
     scale_colour_manual("",values=c('red',"black"))+
     scale_fill_manual("",values=c("grey30",'gray75'))+
     theme_bw(base_size=10) +
     ggtitle('')+
     theme(plot.title = element_text(hjust = 0.5),legend.position="top")

F_Frms <- ggplot() + 
    geom_line(data=EstatusMar,aes(y=Frpr2, x=x, colour = "marzo 2021"), size=0.5)+
    geom_line(data=EstatusSep,aes(y=Frpr1, x=x, colour = "septiembre 2020"), size=0.5)+
    geom_ribbon(data=EstatusMar,aes(ymin=lowerFrpr2, ymax=upperFrpr2, x=x, fill = "IC"), alpha = 0.2)+
    geom_ribbon(data=EstatusSep,aes(ymin=lowerFrpr1, ymax=upperFrpr1, x=x, fill = ""), alpha = 0.2)+
     geom_hline(yintercept = 1,colour=c('green3')) +
     annotate("text", x=2012, y=1+0.25,label=c(expression("F"[RMS]))) +
    labs(x = '', y = expression("F/F"[RMS]),colour='Asesorías',tag="c)")  +
    scale_x_continuous(breaks = seq(from = 1960, to = 2062, by = 2)) +
    scale_colour_manual("",values=c('red',"black"))+
    scale_fill_manual("",values=c("grey30",'gray75'))+
    theme_bw(base_size=10) +
     ggtitle('')+
     theme(plot.title = element_text(hjust = 0.5),legend.position="none")

fig_desnb<- ggplot() + lims(y=c(0,3.5)) +
     geom_polygon(data=densb_bm,aes(x=x, y=y, group=t,alpha=0.9),fill="gray75")+
     geom_polygon(data=densb_bs,aes(x=x, y=y, group=t,alpha=0.9),fill="gray35")+
     geom_line(aes(xbm,ybm), size=0.3,color="red")+
     geom_line(aes(xbs,ybs), size=0.3,color="black")+
     annotate("text", x=c(1,1), y=c(3.4,3.2), colour = c("red","black"), size = 2.5,
              label=c(paste("IC95%_marzo2021= [",round(icbm[1],3),"-",round(icbm[2],3),"]",sep=" "),
                      paste("IC95%_sept2020 = [",round(icbs[1],3),"-",round(icbs[2],3),"]",sep=" "))) +
     labs(x = expression("BD"[last]*"/BD"[RMS]), y = 'Densidad de probabilidad',tag="b)")  +
     scale_colour_manual("",values=c('red',"black"))+
     scale_fill_manual("",values=c("grey30",'gray75'))+
     theme_bw(base_size=10) + 
     theme(plot.title = element_text(hjust = 0.5),legend.position="none")

fig_desnf<- ggplot() + lims(y=c(0,2.5))+
     geom_polygon(data=densb_fm,aes(x=x, y=y, group=t,alpha=0.9,fill = ""),fill="gray75")+
     geom_polygon(data=densb_fs,aes(x=x, y=y, group=t,alpha=0.9),fill="gray35")+
     geom_line(aes(xfm,yfm), size=0.3,color="red")+
     geom_line(aes(xfs,yfs), size=0.3,color="black")+
     annotate("text", x=c(0.9,0.9), y=c(2.5,2.35), colour = c("red","black"), size = 2.5,
              label=c(paste("IC95%_marzo2021 = [",round(icfm[1],3),"-",round(icfm[2],3),"]",sep=" "),
                      paste("IC95%_sept2020  = [",round(icfs[1],3),"-",round(icfs[2],3),"]",sep=" "))) +
     labs(x = expression("F"[last]*"/F"[RMS]), y = 'Densidad de probabilidad',tag="d)")  +
     theme_bw(base_size=10) + 
     theme(plot.title = element_text(hjust = 0.5),legend.position="none")


 {(BD_BDrms / F_Frms)   | (fig_desnb/fig_desnf)} +  plot_layout(ncol=2,widths=c(2,1))
 

```


```{r Tabla_29, echo=T,warning=FALSE}
yearsb<-c("1990/91","1991/92","1992/93","1993/94","1994/95","1995/96","1996/97","1997/98","1998/99","1999/00","2000/01","2001/02","2002/03","2003/04","2004/05","2005/06","2006/07","2007/08","2008/09","2009/10","2010/11","2011/12","2012/13","2013/14","2014/15","2015/16","2016/17","2017/18","2018/19","2019/20",'2020/21')
VarPobl2<- cbind('Años'=yearsb,
                 "$F/F_{RMS_{sept}}$"=c(round(exp(Ft1)/FRMS1,3)),
                 "$F/F_{RMS_{marzo}}$"=c(round(exp(Ft2)/FRMS2,3)),
                 "$BD/BD_{RMS_{sept}}$"=c(round(BD1/BRMS1,3)),
                 "$BD/BD_{RMS_{marzo}}$"=c(round(BD2/BRMS2,3)))
kable(VarPobl2, align = 'c')

#setwd(dir.basedatos)
write.csv(VarPobl2, file="Tabla_22_indicesReduccion.csv")
#setwd(dir.1)

```


```{r Tabla_29b, echo=T,warning=FALSE}
yearsb<-c("1990/91","1991/92","1992/93","1993/94","1994/95","1995/96","1996/97","1997/98","1998/99","1999/00","2000/01","2001/02","2002/03","2003/04","2004/05","2005/06","2006/07","2007/08","2008/09","2009/10","2010/11","2011/12","2012/13","2013/14","2014/15","2015/16","2016/17","2017/18","2018/19","2019/20",'2020/21')

VarPobl2b<- cbind('Años'=yearsb,
                 "$Y/BT_{sept}$"=c(round(rep1$desembarquepred/BT1,3)),
                  "$Y/BT_{marzo}$"=c(round(rep2$desembarquepred/BT2,3)),
                 "$C/N_{sept}$"=c(round(c(rowSums(rep1$pred_Ctot)/rowSums(rep1$N),NA),3)),
                  "$C/N_{marzo}$"=c(round(rowSums(rep2$pred_Ctot)/rowSums(rep2$N),3)))
kable(VarPobl2b, align = 'c')

#setwd(dir.basedatos)
write.csv(VarPobl2b, file="Tabla_23_tasasExplotacion.csv")
#setwd(dir.1)

```


```{r Fig40, warning=F, include=T, message=F, echo=T,fig.height=4,fig.width=4,fig.align="center",fig.path=dir.Fig,dev=fig}
source(paste(dir.fun,"Fn_DiagramaFase2.R",sep=""))
name1<-"Asesoría de Septiembre 2020"
years1<-rep1$years
nyears1<-length(years1)

DiagramaFase2(name1,
             years1[1:nyears1-1],
             SpB1[1:nyears1-1],
             SpBSE1[1:nyears1-1],
             ln_Fyr1[1:nyears1-1],
             ln_FSE1[1:nyears1-1],
             SpB1[nyears1],
             SpBSE1[nyears1],
             ln_Fyr1[nyears1],
             ln_FSE1[nyears1],
             FRMS1,
             BRMS1,
             BLIM1,
             FLIM1,
             color=F,
             dir.1,
             etiqueta=F,
             preliminar=F,
             completo=T)

text(c(SpB1[1]/BRMS1,SpB1[nyears1]/BRMS1,SpB1[nyears1-1]/BRMS1),
     c(exp(ln_Fyr1[1])/FRMS1-0.05,exp(ln_Fyr1[nyears1])/FRMS1-0.05,exp(ln_Fyr1[nyears1-1])/FRMS1+0.05), c("1990/91","2019/20","2018/19"),cex=1.2)

```


```{r Fig41, warning=F, include=T, message=F, echo=T,fig.height=4,fig.width=4,fig.align="center",fig.path=dir.Fig,dev=fig}
source(paste(dir.fun,"Fn_DiagramaFase2.R",sep=""))
name2<-"Asesoría de Marzo 2021"
years2<-rep2$years
nyears2<-length(years2)

DiagramaFase2(name2,
             years2[1:nyears2-1],
             SpB2[1:nyears2-1],
             SpBSE2[1:nyears2-1],
             ln_Fyr2[1:nyears2-1],
             ln_FSE2[1:nyears2-1],
             SpB2[nyears2],
             SpBSE2[nyears2],
             ln_Fyr2[nyears2],
             ln_FSE2[nyears2],
             FRMS2,
             BRMS2,
             BLIM2,
             FLIM2,
             color=F,
             dir.1,
             etiqueta=F,
             preliminar=T,
             completo=F)

text(c(SpB2[1]/BRMS2,SpB2[nyears2]/BRMS2,SpB2[nyears2-1]/BRMS2),
     c(exp(ln_Fyr2[1])/FRMS2-0.05,exp(ln_Fyr2[nyears2])/FRMS2-0.05,exp(ln_Fyr2[nyears2-1])/FRMS2+0.05), c("1990/91","2020/21","2019/20"),cex=1.2)

```


```{r Tabla26, echo=T}
Tabla4.1<-rbind("Año biológico"=c("2019/20","2020/21"),
                "$F_{RMS}$"=c(round(FRMS1,2),round(FRMS2,2)),
                "$BD_{RMS}$"=c(round(BRMS1/10^3,0),round(BRMS2/10^3,0)),
                "$BD_{LIM}$"=c(round(BLIM1/10^3,0),round(BLIM2/10^3,0)),
                "$p(BD_{last}<BD_{RMS})$"=round(c(pa_sept,pa_mar),2),
                "$p(F_{last}>F_{RMS})$"=round(c(pb_sept,pb_mar),2),
                "$p(sobre-explotación)$"=round(c(pc_sept,pc_mar),2),
                "$p(agotado/colapsado)$"=round(c(pd_sept,pd_mar),2),
                "$p(sobrepesca)$"=round(c(pe_sept,pe_mar),2))
colnames(Tabla4.1)<-c("Septiembre 2020","Marzo 2021")
kable(Tabla4.1,align='c')
```

